/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark;

import com.microsoft.rest.RestException;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in JsonSchemaClients.
 */
public interface JsonSchemaClients {
    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Object object if successful.
     */
    Object get(String schemaId);

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Object> getAsync(String schemaId, final ServiceCallback<Object> serviceCallback);

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Object object
     */
    Observable<Object> getAsync(String schemaId);

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Object object
     */
    Observable<ServiceResponse<Object>> getWithServiceResponseAsync(String schemaId);

}
