/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Corresponds to xmpDM.AudioChannelTypeChoice
 */
@JsonAdapter(AudioChannelType.Adapter.class)
public enum AudioChannelType {
  
  MONO("CHANNEL_MONO"),
  
  STEREO("CHANNEL_STEREO"),
  
  _5_1("CHANNEL_5_1"),
  
  _7_1("CHANNEL_7_1"),
  
  _16("CHANNEL_16"),
  
  OTHER("CHANNEL_OTHER");

  private String value;

  AudioChannelType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AudioChannelType fromValue(String text) {
    for (AudioChannelType b : AudioChannelType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AudioChannelType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AudioChannelType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AudioChannelType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AudioChannelType.fromValue(String.valueOf(value));
    }
  }
}

