/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.StoreAudit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Content
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class Content {
  @SerializedName("audit")
  private StoreAudit audit = null;

  @SerializedName("contentSchemaId")
  private String contentSchemaId = null;

  @SerializedName("layerSchemaIds")
  private List<String> layerSchemaIds = null;

  @SerializedName("displayValues")
  private Map<String, String> displayValues = null;

  @SerializedName("id")
  private String id = null;

  public Content audit(StoreAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public StoreAudit getAudit() {
    return audit;
  }

  public void setAudit(StoreAudit audit) {
    this.audit = audit;
  }

  public Content contentSchemaId(String contentSchemaId) {
    this.contentSchemaId = contentSchemaId;
    return this;
  }

   /**
   * The id of the schema with schema type content.
   * @return contentSchemaId
  **/
  @ApiModelProperty(value = "The id of the schema with schema type content.")
  public String getContentSchemaId() {
    return contentSchemaId;
  }

  public void setContentSchemaId(String contentSchemaId) {
    this.contentSchemaId = contentSchemaId;
  }

  public Content layerSchemaIds(List<String> layerSchemaIds) {
    this.layerSchemaIds = layerSchemaIds;
    return this;
  }

  public Content addLayerSchemaIdsItem(String layerSchemaIdsItem) {
    if (this.layerSchemaIds == null) {
      this.layerSchemaIds = new ArrayList<String>();
    }
    this.layerSchemaIds.add(layerSchemaIdsItem);
    return this;
  }

   /**
   * An optional id list of schemas with schema type layer.
   * @return layerSchemaIds
  **/
  @ApiModelProperty(value = "An optional id list of schemas with schema type layer.")
  public List<String> getLayerSchemaIds() {
    return layerSchemaIds;
  }

  public void setLayerSchemaIds(List<String> layerSchemaIds) {
    this.layerSchemaIds = layerSchemaIds;
  }

  public Content displayValues(Map<String, String> displayValues) {
    this.displayValues = displayValues;
    return this;
  }

  public Content putDisplayValuesItem(String key, String displayValuesItem) {
    if (this.displayValues == null) {
      this.displayValues = new HashMap<String, String>();
    }
    this.displayValues.put(key, displayValuesItem);
    return this;
  }

   /**
   * Contains display values of the specified language, rendered according to the content schema&#39;s display pattern configuration.
   * @return displayValues
  **/
  @ApiModelProperty(value = "Contains display values of the specified language, rendered according to the content schema's display pattern configuration.")
  public Map<String, String> getDisplayValues() {
    return displayValues;
  }

  public void setDisplayValues(Map<String, String> displayValues) {
    this.displayValues = displayValues;
  }

  public Content id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Content content = (Content) o;
    return Objects.equals(this.audit, content.audit) &&
        Objects.equals(this.contentSchemaId, content.contentSchemaId) &&
        Objects.equals(this.layerSchemaIds, content.layerSchemaIds) &&
        Objects.equals(this.displayValues, content.displayValues) &&
        Objects.equals(this.id, content.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audit, contentSchemaId, layerSchemaIds, displayValues, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Content {\n");
    
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("    contentSchemaId: ").append(toIndentedString(contentSchemaId)).append("\n");
    sb.append("    layerSchemaIds: ").append(toIndentedString(layerSchemaIds)).append("\n");
    sb.append("    displayValues: ").append(toIndentedString(displayValues)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

