/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ContentType;
import io.swagger.client.model.DataDictionary;
import io.swagger.client.model.Output;
import io.swagger.client.model.StoreAudit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ContentDetail2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class ContentDetail2 {
  @SerializedName("trashed")
  private Boolean trashed = null;

  @SerializedName("contentSchemaId")
  private String contentSchemaId = null;

  @SerializedName("layerSchemaIds")
  private List<String> layerSchemaIds = null;

  @SerializedName("content")
  private DataDictionary content = null;

  @SerializedName("metadata")
  private DataDictionary metadata = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("contentPermissionSetIds")
  private List<String> contentPermissionSetIds = null;

  @SerializedName("outputs")
  private List<Output> outputs = null;

  @SerializedName("audit")
  private StoreAudit audit = null;

  @SerializedName("ownerTokenId")
  private String ownerTokenId = null;

  @SerializedName("contentType")
  private ContentType contentType = null;

  public ContentDetail2 trashed(Boolean trashed) {
    this.trashed = trashed;
    return this;
  }

   /**
   * Get trashed
   * @return trashed
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getTrashed() {
    return trashed;
  }

  public void setTrashed(Boolean trashed) {
    this.trashed = trashed;
  }

  public ContentDetail2 contentSchemaId(String contentSchemaId) {
    this.contentSchemaId = contentSchemaId;
    return this;
  }

   /**
   * The id of the schema with schema type content.
   * @return contentSchemaId
  **/
  @ApiModelProperty(value = "The id of the schema with schema type content.")
  public String getContentSchemaId() {
    return contentSchemaId;
  }

  public void setContentSchemaId(String contentSchemaId) {
    this.contentSchemaId = contentSchemaId;
  }

  public ContentDetail2 layerSchemaIds(List<String> layerSchemaIds) {
    this.layerSchemaIds = layerSchemaIds;
    return this;
  }

  public ContentDetail2 addLayerSchemaIdsItem(String layerSchemaIdsItem) {
    if (this.layerSchemaIds == null) {
      this.layerSchemaIds = new ArrayList<String>();
    }
    this.layerSchemaIds.add(layerSchemaIdsItem);
    return this;
  }

   /**
   * An optional id list of schemas with type layer.
   * @return layerSchemaIds
  **/
  @ApiModelProperty(value = "An optional id list of schemas with type layer.")
  public List<String> getLayerSchemaIds() {
    return layerSchemaIds;
  }

  public void setLayerSchemaIds(List<String> layerSchemaIds) {
    this.layerSchemaIds = layerSchemaIds;
  }

  public ContentDetail2 content(DataDictionary content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public DataDictionary getContent() {
    return content;
  }

  public void setContent(DataDictionary content) {
    this.content = content;
  }

  public ContentDetail2 metadata(DataDictionary metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public DataDictionary getMetadata() {
    return metadata;
  }

  public void setMetadata(DataDictionary metadata) {
    this.metadata = metadata;
  }

  public ContentDetail2 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ContentDetail2 contentPermissionSetIds(List<String> contentPermissionSetIds) {
    this.contentPermissionSetIds = contentPermissionSetIds;
    return this;
  }

  public ContentDetail2 addContentPermissionSetIdsItem(String contentPermissionSetIdsItem) {
    if (this.contentPermissionSetIds == null) {
      this.contentPermissionSetIds = new ArrayList<String>();
    }
    this.contentPermissionSetIds.add(contentPermissionSetIdsItem);
    return this;
  }

   /**
   * An optional id list of content permission sets. Controls content accessibility outside of content ownership.
   * @return contentPermissionSetIds
  **/
  @ApiModelProperty(value = "An optional id list of content permission sets. Controls content accessibility outside of content ownership.")
  public List<String> getContentPermissionSetIds() {
    return contentPermissionSetIds;
  }

  public void setContentPermissionSetIds(List<String> contentPermissionSetIds) {
    this.contentPermissionSetIds = contentPermissionSetIds;
  }

  public ContentDetail2 outputs(List<Output> outputs) {
    this.outputs = outputs;
    return this;
  }

  public ContentDetail2 addOutputsItem(Output outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<Output>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Get outputs
   * @return outputs
  **/
  @ApiModelProperty(value = "")
  public List<Output> getOutputs() {
    return outputs;
  }

  public void setOutputs(List<Output> outputs) {
    this.outputs = outputs;
  }

  public ContentDetail2 audit(StoreAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public StoreAudit getAudit() {
    return audit;
  }

  public void setAudit(StoreAudit audit) {
    this.audit = audit;
  }

  public ContentDetail2 ownerTokenId(String ownerTokenId) {
    this.ownerTokenId = ownerTokenId;
    return this;
  }

   /**
   * Get ownerTokenId
   * @return ownerTokenId
  **/
  @ApiModelProperty(value = "")
  public String getOwnerTokenId() {
    return ownerTokenId;
  }

  public void setOwnerTokenId(String ownerTokenId) {
    this.ownerTokenId = ownerTokenId;
  }

  public ContentDetail2 contentType(ContentType contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(required = true, value = "")
  public ContentType getContentType() {
    return contentType;
  }

  public void setContentType(ContentType contentType) {
    this.contentType = contentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentDetail2 contentDetail2 = (ContentDetail2) o;
    return Objects.equals(this.trashed, contentDetail2.trashed) &&
        Objects.equals(this.contentSchemaId, contentDetail2.contentSchemaId) &&
        Objects.equals(this.layerSchemaIds, contentDetail2.layerSchemaIds) &&
        Objects.equals(this.content, contentDetail2.content) &&
        Objects.equals(this.metadata, contentDetail2.metadata) &&
        Objects.equals(this.id, contentDetail2.id) &&
        Objects.equals(this.contentPermissionSetIds, contentDetail2.contentPermissionSetIds) &&
        Objects.equals(this.outputs, contentDetail2.outputs) &&
        Objects.equals(this.audit, contentDetail2.audit) &&
        Objects.equals(this.ownerTokenId, contentDetail2.ownerTokenId) &&
        Objects.equals(this.contentType, contentDetail2.contentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trashed, contentSchemaId, layerSchemaIds, content, metadata, id, contentPermissionSetIds, outputs, audit, ownerTokenId, contentType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentDetail2 {\n");
    
    sb.append("    trashed: ").append(toIndentedString(trashed)).append("\n");
    sb.append("    contentSchemaId: ").append(toIndentedString(contentSchemaId)).append("\n");
    sb.append("    layerSchemaIds: ").append(toIndentedString(layerSchemaIds)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    contentPermissionSetIds: ").append(toIndentedString(contentPermissionSetIds)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("    ownerTokenId: ").append(toIndentedString(ownerTokenId)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

