/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ImageSupplierInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class ImageSupplierInfo {
  @SerializedName("imageSupplierName")
  private String imageSupplierName = null;

  @SerializedName("imageSupplierID")
  private String imageSupplierID = null;

  public ImageSupplierInfo imageSupplierName(String imageSupplierName) {
    this.imageSupplierName = imageSupplierName;
    return this;
  }

   /**
   * Get imageSupplierName
   * @return imageSupplierName
  **/
  @ApiModelProperty(value = "")
  public String getImageSupplierName() {
    return imageSupplierName;
  }

  public void setImageSupplierName(String imageSupplierName) {
    this.imageSupplierName = imageSupplierName;
  }

  public ImageSupplierInfo imageSupplierID(String imageSupplierID) {
    this.imageSupplierID = imageSupplierID;
    return this;
  }

   /**
   * Get imageSupplierID
   * @return imageSupplierID
  **/
  @ApiModelProperty(value = "")
  public String getImageSupplierID() {
    return imageSupplierID;
  }

  public void setImageSupplierID(String imageSupplierID) {
    this.imageSupplierID = imageSupplierID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSupplierInfo imageSupplierInfo = (ImageSupplierInfo) o;
    return Objects.equals(this.imageSupplierName, imageSupplierInfo.imageSupplierName) &&
        Objects.equals(this.imageSupplierID, imageSupplierInfo.imageSupplierID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageSupplierName, imageSupplierID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSupplierInfo {\n");
    
    sb.append("    imageSupplierName: ").append(toIndentedString(imageSupplierName)).append("\n");
    sb.append("    imageSupplierID: ").append(toIndentedString(imageSupplierID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

