/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MetadataValuesSchemaUpdateCommand;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ListItemFieldsUpdateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class ListItemFieldsUpdateRequest {
  @SerializedName("listItemIds")
  private List<String> listItemIds = null;

  @SerializedName("changeCommands")
  private List<MetadataValuesSchemaUpdateCommand> changeCommands = null;

  public ListItemFieldsUpdateRequest listItemIds(List<String> listItemIds) {
    this.listItemIds = listItemIds;
    return this;
  }

  public ListItemFieldsUpdateRequest addListItemIdsItem(String listItemIdsItem) {
    if (this.listItemIds == null) {
      this.listItemIds = new ArrayList<String>();
    }
    this.listItemIds.add(listItemIdsItem);
    return this;
  }

   /**
   * The ids of the list items whose fields need to be updated
   * @return listItemIds
  **/
  @ApiModelProperty(value = "The ids of the list items whose fields need to be updated")
  public List<String> getListItemIds() {
    return listItemIds;
  }

  public void setListItemIds(List<String> listItemIds) {
    this.listItemIds = listItemIds;
  }

  public ListItemFieldsUpdateRequest changeCommands(List<MetadataValuesSchemaUpdateCommand> changeCommands) {
    this.changeCommands = changeCommands;
    return this;
  }

  public ListItemFieldsUpdateRequest addChangeCommandsItem(MetadataValuesSchemaUpdateCommand changeCommandsItem) {
    if (this.changeCommands == null) {
      this.changeCommands = new ArrayList<MetadataValuesSchemaUpdateCommand>();
    }
    this.changeCommands.add(changeCommandsItem);
    return this;
  }

   /**
   * The change commads to be applied to the list items
   * @return changeCommands
  **/
  @ApiModelProperty(value = "The change commads to be applied to the list items")
  public List<MetadataValuesSchemaUpdateCommand> getChangeCommands() {
    return changeCommands;
  }

  public void setChangeCommands(List<MetadataValuesSchemaUpdateCommand> changeCommands) {
    this.changeCommands = changeCommands;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListItemFieldsUpdateRequest listItemFieldsUpdateRequest = (ListItemFieldsUpdateRequest) o;
    return Objects.equals(this.listItemIds, listItemFieldsUpdateRequest.listItemIds) &&
        Objects.equals(this.changeCommands, listItemFieldsUpdateRequest.changeCommands);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listItemIds, changeCommands);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListItemFieldsUpdateRequest {\n");
    
    sb.append("    listItemIds: ").append(toIndentedString(listItemIds)).append("\n");
    sb.append("    changeCommands: ").append(toIndentedString(changeCommands)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

