/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MetadataValuesChangeCommandBase;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MetadataValuesChangeRequestBase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")

public class MetadataValuesChangeRequestBase {
  @SerializedName("changeCommands")
  private List<MetadataValuesChangeCommandBase> changeCommands = null;

  @SerializedName("kind")
  private String kind = null;

  public MetadataValuesChangeRequestBase changeCommands(List<MetadataValuesChangeCommandBase> changeCommands) {
    this.changeCommands = changeCommands;
    return this;
  }

  public MetadataValuesChangeRequestBase addChangeCommandsItem(MetadataValuesChangeCommandBase changeCommandsItem) {
    if (this.changeCommands == null) {
      this.changeCommands = new ArrayList<MetadataValuesChangeCommandBase>();
    }
    this.changeCommands.add(changeCommandsItem);
    return this;
  }

   /**
   * A container for all change commads.
   * @return changeCommands
  **/
  @ApiModelProperty(value = "A container for all change commads.")
  public List<MetadataValuesChangeCommandBase> getChangeCommands() {
    return changeCommands;
  }

  public void setChangeCommands(List<MetadataValuesChangeCommandBase> changeCommands) {
    this.changeCommands = changeCommands;
  }

  public MetadataValuesChangeRequestBase kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(required = true, value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataValuesChangeRequestBase metadataValuesChangeRequestBase = (MetadataValuesChangeRequestBase) o;
    return Objects.equals(this.changeCommands, metadataValuesChangeRequestBase.changeCommands) &&
        Objects.equals(this.kind, metadataValuesChangeRequestBase.kind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeCommands, kind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataValuesChangeRequestBase {\n");
    
    sb.append("    changeCommands: ").append(toIndentedString(changeCommands)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

