/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Corresponds to tiff.OrientationChoice
 */
@JsonAdapter(Orientation.Adapter.class)
public enum Orientation {
  
  NONE("None"),
  
  TOPROWLEFTCOLUMN("TopRowLeftColumn"),
  
  TOPROWRIGHTCOLUMN("TopRowRightColumn"),
  
  BOTTOMROWLEFTCOLUMN("BottomRowLeftColumn"),
  
  BOTTOMROWRIGHTCOLUMN("BottomRowRightColumn"),
  
  LEFTROWTOPCOLUMN("LeftRowTopColumn"),
  
  RIGHTROWTOPCOLUMN("RightRowTopColumn"),
  
  RIGHTROWBOTTOMCOLUMN("RightRowBottomColumn"),
  
  LEFTROWBOTTOMCOLUMN("LeftRowBottomColumn"),
  
  UNKNOWN("Unknown");

  private String value;

  Orientation(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Orientation fromValue(String text) {
    for (Orientation b : Orientation.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Orientation> {
    @Override
    public void write(final JsonWriter jsonWriter, final Orientation enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Orientation read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Orientation.fromValue(String.valueOf(value));
    }
  }
}

