/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Pdf
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class Pdf {
  @SerializedName("keywords")
  private String keywords = null;

  @SerializedName("pdfVersion")
  private String pdfVersion = null;

  @SerializedName("producer")
  private String producer = null;

  @SerializedName("trapped")
  private Boolean trapped = null;

  public Pdf keywords(String keywords) {
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @ApiModelProperty(value = "")
  public String getKeywords() {
    return keywords;
  }

  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  public Pdf pdfVersion(String pdfVersion) {
    this.pdfVersion = pdfVersion;
    return this;
  }

   /**
   * Get pdfVersion
   * @return pdfVersion
  **/
  @ApiModelProperty(value = "")
  public String getPdfVersion() {
    return pdfVersion;
  }

  public void setPdfVersion(String pdfVersion) {
    this.pdfVersion = pdfVersion;
  }

  public Pdf producer(String producer) {
    this.producer = producer;
    return this;
  }

   /**
   * Get producer
   * @return producer
  **/
  @ApiModelProperty(value = "")
  public String getProducer() {
    return producer;
  }

  public void setProducer(String producer) {
    this.producer = producer;
  }

  public Pdf trapped(Boolean trapped) {
    this.trapped = trapped;
    return this;
  }

   /**
   * Get trapped
   * @return trapped
  **/
  @ApiModelProperty(value = "")
  public Boolean getTrapped() {
    return trapped;
  }

  public void setTrapped(Boolean trapped) {
    this.trapped = trapped;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pdf pdf = (Pdf) o;
    return Objects.equals(this.keywords, pdf.keywords) &&
        Objects.equals(this.pdfVersion, pdf.pdfVersion) &&
        Objects.equals(this.producer, pdf.producer) &&
        Objects.equals(this.trapped, pdf.trapped);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keywords, pdfVersion, producer, trapped);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pdf {\n");
    
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    pdfVersion: ").append(toIndentedString(pdfVersion)).append("\n");
    sb.append("    producer: ").append(toIndentedString(producer)).append("\n");
    sb.append("    trapped: ").append(toIndentedString(trapped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

