/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RegistryEntryInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class RegistryEntryInfo {
  @SerializedName("registryItemIdentifier")
  private String registryItemIdentifier = null;

  @SerializedName("registryOrganisationIdentifier")
  private String registryOrganisationIdentifier = null;

  public RegistryEntryInfo registryItemIdentifier(String registryItemIdentifier) {
    this.registryItemIdentifier = registryItemIdentifier;
    return this;
  }

   /**
   * Get registryItemIdentifier
   * @return registryItemIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getRegistryItemIdentifier() {
    return registryItemIdentifier;
  }

  public void setRegistryItemIdentifier(String registryItemIdentifier) {
    this.registryItemIdentifier = registryItemIdentifier;
  }

  public RegistryEntryInfo registryOrganisationIdentifier(String registryOrganisationIdentifier) {
    this.registryOrganisationIdentifier = registryOrganisationIdentifier;
    return this;
  }

   /**
   * Get registryOrganisationIdentifier
   * @return registryOrganisationIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getRegistryOrganisationIdentifier() {
    return registryOrganisationIdentifier;
  }

  public void setRegistryOrganisationIdentifier(String registryOrganisationIdentifier) {
    this.registryOrganisationIdentifier = registryOrganisationIdentifier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistryEntryInfo registryEntryInfo = (RegistryEntryInfo) o;
    return Objects.equals(this.registryItemIdentifier, registryEntryInfo.registryItemIdentifier) &&
        Objects.equals(this.registryOrganisationIdentifier, registryEntryInfo.registryOrganisationIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(registryItemIdentifier, registryOrganisationIdentifier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistryEntryInfo {\n");
    
    sb.append("    registryItemIdentifier: ").append(toIndentedString(registryItemIdentifier)).append("\n");
    sb.append("    registryOrganisationIdentifier: ").append(toIndentedString(registryOrganisationIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

