/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.StoreAudit;
import io.swagger.client.model.TransferState;
import io.swagger.client.model.TransferType;
import java.io.IOException;

/**
 * TransferDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-04T14:36:42.044Z")
public class TransferDetail {
  @SerializedName("id")
  private String id = null;

  @SerializedName("rev")
  private String rev = null;

  @SerializedName("audit")
  private StoreAudit audit = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("state")
  private TransferState state = null;

  @SerializedName("businessProcessId")
  private String businessProcessId = null;

  @SerializedName("transferType")
  private TransferType transferType = null;

  @SerializedName("itemProgress")
  private Long itemProgress = null;

  @SerializedName("itemCount")
  private Long itemCount = null;

  @SerializedName("itemsFailed")
  private Long itemsFailed = null;

  @SerializedName("itemsCancelled")
  private Long itemsCancelled = null;

  @SerializedName("lastProgressStamp")
  private Long lastProgressStamp = null;

  @SerializedName("fileTransferCount")
  private Long fileTransferCount = null;

  public TransferDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TransferDetail rev(String rev) {
    this.rev = rev;
    return this;
  }

   /**
   * Get rev
   * @return rev
  **/
  @ApiModelProperty(value = "")
  public String getRev() {
    return rev;
  }

  public void setRev(String rev) {
    this.rev = rev;
  }

  public TransferDetail audit(StoreAudit audit) {
    this.audit = audit;
    return this;
  }

   /**
   * Get audit
   * @return audit
  **/
  @ApiModelProperty(value = "")
  public StoreAudit getAudit() {
    return audit;
  }

  public void setAudit(StoreAudit audit) {
    this.audit = audit;
  }

  public TransferDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TransferDetail state(TransferState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(required = true, value = "")
  public TransferState getState() {
    return state;
  }

  public void setState(TransferState state) {
    this.state = state;
  }

  public TransferDetail businessProcessId(String businessProcessId) {
    this.businessProcessId = businessProcessId;
    return this;
  }

   /**
   * Get businessProcessId
   * @return businessProcessId
  **/
  @ApiModelProperty(value = "")
  public String getBusinessProcessId() {
    return businessProcessId;
  }

  public void setBusinessProcessId(String businessProcessId) {
    this.businessProcessId = businessProcessId;
  }

  public TransferDetail transferType(TransferType transferType) {
    this.transferType = transferType;
    return this;
  }

   /**
   * Get transferType
   * @return transferType
  **/
  @ApiModelProperty(required = true, value = "")
  public TransferType getTransferType() {
    return transferType;
  }

  public void setTransferType(TransferType transferType) {
    this.transferType = transferType;
  }

  public TransferDetail itemProgress(Long itemProgress) {
    this.itemProgress = itemProgress;
    return this;
  }

   /**
   * Get itemProgress
   * @return itemProgress
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getItemProgress() {
    return itemProgress;
  }

  public void setItemProgress(Long itemProgress) {
    this.itemProgress = itemProgress;
  }

  public TransferDetail itemCount(Long itemCount) {
    this.itemCount = itemCount;
    return this;
  }

   /**
   * Get itemCount
   * @return itemCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getItemCount() {
    return itemCount;
  }

  public void setItemCount(Long itemCount) {
    this.itemCount = itemCount;
  }

  public TransferDetail itemsFailed(Long itemsFailed) {
    this.itemsFailed = itemsFailed;
    return this;
  }

   /**
   * Get itemsFailed
   * @return itemsFailed
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getItemsFailed() {
    return itemsFailed;
  }

  public void setItemsFailed(Long itemsFailed) {
    this.itemsFailed = itemsFailed;
  }

  public TransferDetail itemsCancelled(Long itemsCancelled) {
    this.itemsCancelled = itemsCancelled;
    return this;
  }

   /**
   * Get itemsCancelled
   * @return itemsCancelled
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getItemsCancelled() {
    return itemsCancelled;
  }

  public void setItemsCancelled(Long itemsCancelled) {
    this.itemsCancelled = itemsCancelled;
  }

  public TransferDetail lastProgressStamp(Long lastProgressStamp) {
    this.lastProgressStamp = lastProgressStamp;
    return this;
  }

   /**
   * Get lastProgressStamp
   * @return lastProgressStamp
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getLastProgressStamp() {
    return lastProgressStamp;
  }

  public void setLastProgressStamp(Long lastProgressStamp) {
    this.lastProgressStamp = lastProgressStamp;
  }

  public TransferDetail fileTransferCount(Long fileTransferCount) {
    this.fileTransferCount = fileTransferCount;
    return this;
  }

   /**
   * Get fileTransferCount
   * @return fileTransferCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getFileTransferCount() {
    return fileTransferCount;
  }

  public void setFileTransferCount(Long fileTransferCount) {
    this.fileTransferCount = fileTransferCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferDetail transferDetail = (TransferDetail) o;
    return Objects.equals(this.id, transferDetail.id) &&
        Objects.equals(this.rev, transferDetail.rev) &&
        Objects.equals(this.audit, transferDetail.audit) &&
        Objects.equals(this.name, transferDetail.name) &&
        Objects.equals(this.state, transferDetail.state) &&
        Objects.equals(this.businessProcessId, transferDetail.businessProcessId) &&
        Objects.equals(this.transferType, transferDetail.transferType) &&
        Objects.equals(this.itemProgress, transferDetail.itemProgress) &&
        Objects.equals(this.itemCount, transferDetail.itemCount) &&
        Objects.equals(this.itemsFailed, transferDetail.itemsFailed) &&
        Objects.equals(this.itemsCancelled, transferDetail.itemsCancelled) &&
        Objects.equals(this.lastProgressStamp, transferDetail.lastProgressStamp) &&
        Objects.equals(this.fileTransferCount, transferDetail.fileTransferCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rev, audit, name, state, businessProcessId, transferType, itemProgress, itemCount, itemsFailed, itemsCancelled, lastProgressStamp, fileTransferCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    audit: ").append(toIndentedString(audit)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    businessProcessId: ").append(toIndentedString(businessProcessId)).append("\n");
    sb.append("    transferType: ").append(toIndentedString(transferType)).append("\n");
    sb.append("    itemProgress: ").append(toIndentedString(itemProgress)).append("\n");
    sb.append("    itemCount: ").append(toIndentedString(itemCount)).append("\n");
    sb.append("    itemsFailed: ").append(toIndentedString(itemsFailed)).append("\n");
    sb.append("    itemsCancelled: ").append(toIndentedString(itemsCancelled)).append("\n");
    sb.append("    lastProgressStamp: ").append(toIndentedString(lastProgressStamp)).append("\n");
    sb.append("    fileTransferCount: ").append(toIndentedString(fileTransferCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

