/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Corresponds to xmpDM.VideoColorSpaceChoice
 */
@JsonAdapter(VideoColorSpace.Adapter.class)
public enum VideoColorSpace {
  
  SRGB("COLOR_SPACE_SRGB"),
  
  CCIR_601("COLOR_SPACE_CCIR_601"),
  
  CCIR_709("COLOR_SPACE_CCIR_709");

  private String value;

  VideoColorSpace(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static VideoColorSpace fromValue(String text) {
    for (VideoColorSpace b : VideoColorSpace.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<VideoColorSpace> {
    @Override
    public void write(final JsonWriter jsonWriter, final VideoColorSpace enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public VideoColorSpace read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return VideoColorSpace.fromValue(String.valueOf(value));
    }
  }
}

