/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ContentDeactivateRequest model.
 */
public class ContentDeactivateRequest {
    /**
     * The contentIds property.
     */
    @JsonProperty(value = "contentIds")
    private List<String> contentIds;

    /**
     * The resolve property.
     */
    @JsonProperty(value = "resolve", required = true)
    private boolean resolve;

    /**
     * The displayPatternIds property.
     */
    @JsonProperty(value = "displayPatternIds")
    private List<String> displayPatternIds;

    /**
     * The forceReferenceRemoval property.
     */
    @JsonProperty(value = "forceReferenceRemoval", required = true)
    private boolean forceReferenceRemoval;

    /**
     * Get the contentIds value.
     *
     * @return the contentIds value
     */
    public List<String> contentIds() {
        return this.contentIds;
    }

    /**
     * Set the contentIds value.
     *
     * @param contentIds the contentIds value to set
     * @return the ContentDeactivateRequest object itself.
     */
    public ContentDeactivateRequest withContentIds(List<String> contentIds) {
        this.contentIds = contentIds;
        return this;
    }

    /**
     * Get the resolve value.
     *
     * @return the resolve value
     */
    public boolean resolve() {
        return this.resolve;
    }

    /**
     * Set the resolve value.
     *
     * @param resolve the resolve value to set
     * @return the ContentDeactivateRequest object itself.
     */
    public ContentDeactivateRequest withResolve(boolean resolve) {
        this.resolve = resolve;
        return this;
    }

    /**
     * Get the displayPatternIds value.
     *
     * @return the displayPatternIds value
     */
    public List<String> displayPatternIds() {
        return this.displayPatternIds;
    }

    /**
     * Set the displayPatternIds value.
     *
     * @param displayPatternIds the displayPatternIds value to set
     * @return the ContentDeactivateRequest object itself.
     */
    public ContentDeactivateRequest withDisplayPatternIds(List<String> displayPatternIds) {
        this.displayPatternIds = displayPatternIds;
        return this;
    }

    /**
     * Get the forceReferenceRemoval value.
     *
     * @return the forceReferenceRemoval value
     */
    public boolean forceReferenceRemoval() {
        return this.forceReferenceRemoval;
    }

    /**
     * Set the forceReferenceRemoval value.
     *
     * @param forceReferenceRemoval the forceReferenceRemoval value to set
     * @return the ContentDeactivateRequest object itself.
     */
    public ContentDeactivateRequest withForceReferenceRemoval(boolean forceReferenceRemoval) {
        this.forceReferenceRemoval = forceReferenceRemoval;
        return this;
    }

}
