/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ContentFieldsUpdateRequest model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ContentFieldsUpdateRequest")
public class ContentFieldsUpdateRequest extends MetadataValuesChangeRequestBase {
    /**
     * The ids of the content documents.
     */
    @JsonProperty(value = "contentIds")
    private List<String> contentIds;

    /**
     * Get the contentIds value.
     *
     * @return the contentIds value
     */
    public List<String> contentIds() {
        return this.contentIds;
    }

    /**
     * Set the contentIds value.
     *
     * @param contentIds the contentIds value to set
     * @return the ContentFieldsUpdateRequest object itself.
     */
    public ContentFieldsUpdateRequest withContentIds(List<String> contentIds) {
        this.contentIds = contentIds;
        return this;
    }

}
