/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The CustomerViolationException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("CustomerViolationException")
public class CustomerViolationException extends PictureparkException {
    /**
     * The expectedCustomerId property.
     */
    @JsonProperty(value = "expectedCustomerId")
    private String expectedCustomerId;

    /**
     * The currentCustomerId property.
     */
    @JsonProperty(value = "currentCustomerId")
    private String currentCustomerId;

    /**
     * Get the expectedCustomerId value.
     *
     * @return the expectedCustomerId value
     */
    public String expectedCustomerId() {
        return this.expectedCustomerId;
    }

    /**
     * Set the expectedCustomerId value.
     *
     * @param expectedCustomerId the expectedCustomerId value to set
     * @return the CustomerViolationException object itself.
     */
    public CustomerViolationException withExpectedCustomerId(String expectedCustomerId) {
        this.expectedCustomerId = expectedCustomerId;
        return this;
    }

    /**
     * Get the currentCustomerId value.
     *
     * @return the currentCustomerId value
     */
    public String currentCustomerId() {
        return this.currentCustomerId;
    }

    /**
     * Set the currentCustomerId value.
     *
     * @param currentCustomerId the currentCustomerId value to set
     * @return the CustomerViolationException object itself.
     */
    public CustomerViolationException withCurrentCustomerId(String currentCustomerId) {
        this.currentCustomerId = currentCustomerId;
        return this;
    }

}
