/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CustomerServiceProviderConfiguration model.
 */
public class CustomerServiceProviderConfiguration {
    /**
     * The serviceProviderId property.
     */
    @JsonProperty(value = "serviceProviderId")
    private String serviceProviderId;

    /**
     * The customerId property.
     */
    @JsonProperty(value = "customerId")
    private String customerId;

    /**
     * The userRoleIds property.
     */
    @JsonProperty(value = "userRoleIds")
    private List<String> userRoleIds;

    /**
     * The settings property.
     */
    @JsonProperty(value = "settings")
    private String settings;

    /**
     * Get the serviceProviderId value.
     *
     * @return the serviceProviderId value
     */
    public String serviceProviderId() {
        return this.serviceProviderId;
    }

    /**
     * Set the serviceProviderId value.
     *
     * @param serviceProviderId the serviceProviderId value to set
     * @return the CustomerServiceProviderConfiguration object itself.
     */
    public CustomerServiceProviderConfiguration withServiceProviderId(String serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
        return this;
    }

    /**
     * Get the customerId value.
     *
     * @return the customerId value
     */
    public String customerId() {
        return this.customerId;
    }

    /**
     * Set the customerId value.
     *
     * @param customerId the customerId value to set
     * @return the CustomerServiceProviderConfiguration object itself.
     */
    public CustomerServiceProviderConfiguration withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Get the userRoleIds value.
     *
     * @return the userRoleIds value
     */
    public List<String> userRoleIds() {
        return this.userRoleIds;
    }

    /**
     * Set the userRoleIds value.
     *
     * @param userRoleIds the userRoleIds value to set
     * @return the CustomerServiceProviderConfiguration object itself.
     */
    public CustomerServiceProviderConfiguration withUserRoleIds(List<String> userRoleIds) {
        this.userRoleIds = userRoleIds;
        return this;
    }

    /**
     * Get the settings value.
     *
     * @return the settings value
     */
    public String settings() {
        return this.settings;
    }

    /**
     * Set the settings value.
     *
     * @param settings the settings value to set
     * @return the CustomerServiceProviderConfiguration object itself.
     */
    public CustomerServiceProviderConfiguration withSettings(String settings) {
        this.settings = settings;
        return this;
    }

}
