/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The DuplicateAliasException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("DuplicateAliasException")
public class DuplicateAliasException extends PictureparkException {
    /**
     * The indexAlias property.
     */
    @JsonProperty(value = "indexAlias")
    private String indexAlias;

    /**
     * Get the indexAlias value.
     *
     * @return the indexAlias value
     */
    public String indexAlias() {
        return this.indexAlias;
    }

    /**
     * Set the indexAlias value.
     *
     * @param indexAlias the indexAlias value to set
     * @return the DuplicateAliasException object itself.
     */
    public DuplicateAliasException withIndexAlias(String indexAlias) {
        this.indexAlias = indexAlias;
        return this;
    }

}
