/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The FieldDecimal model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("FieldDecimal")
public class FieldDecimal extends FieldBase {
    /**
     * The pattern property.
     */
    @JsonProperty(value = "pattern")
    private String pattern;

    /**
     * Defines the lowest possible value.
     */
    @JsonProperty(value = "minimum")
    private BigDecimal minimum;

    /**
     * Defines the highest possible value.
     */
    @JsonProperty(value = "maximum")
    private BigDecimal maximum;

    /**
     * Priorizes search results. SimpleSearch must be true.
     */
    @JsonProperty(value = "boost", required = true)
    private double boost;

    /**
     * Get the pattern value.
     *
     * @return the pattern value
     */
    public String pattern() {
        return this.pattern;
    }

    /**
     * Set the pattern value.
     *
     * @param pattern the pattern value to set
     * @return the FieldDecimal object itself.
     */
    public FieldDecimal withPattern(String pattern) {
        this.pattern = pattern;
        return this;
    }

    /**
     * Get the minimum value.
     *
     * @return the minimum value
     */
    public BigDecimal minimum() {
        return this.minimum;
    }

    /**
     * Set the minimum value.
     *
     * @param minimum the minimum value to set
     * @return the FieldDecimal object itself.
     */
    public FieldDecimal withMinimum(BigDecimal minimum) {
        this.minimum = minimum;
        return this;
    }

    /**
     * Get the maximum value.
     *
     * @return the maximum value
     */
    public BigDecimal maximum() {
        return this.maximum;
    }

    /**
     * Set the maximum value.
     *
     * @param maximum the maximum value to set
     * @return the FieldDecimal object itself.
     */
    public FieldDecimal withMaximum(BigDecimal maximum) {
        this.maximum = maximum;
        return this;
    }

    /**
     * Get the boost value.
     *
     * @return the boost value
     */
    public double boost() {
        return this.boost;
    }

    /**
     * Set the boost value.
     *
     * @param boost the boost value to set
     * @return the FieldDecimal object itself.
     */
    public FieldDecimal withBoost(double boost) {
        this.boost = boost;
        return this;
    }

}
