/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The FieldGeoPoint model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("FieldGeoPoint")
public class FieldGeoPoint extends FieldBase {
    /**
     * Priorizes search results. SimpleSearch must be true.
     */
    @JsonProperty(value = "boost", required = true)
    private double boost;

    /**
     * Get the boost value.
     *
     * @return the boost value
     */
    public double boost() {
        return this.boost;
    }

    /**
     * Set the boost value.
     *
     * @param boost the boost value to set
     * @return the FieldGeoPoint object itself.
     */
    public FieldGeoPoint withBoost(double boost) {
        this.boost = boost;
        return this;
    }

}
