/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The FileTransferSearchResult model.
 */
public class FileTransferSearchResult extends SearchBehaviourBaseResultOfFileTransfer {
    /**
     * The elapsedMilliseconds property.
     */
    @JsonProperty(value = "elapsedMilliseconds", required = true)
    private long elapsedMilliseconds;

    /**
     * Get the elapsedMilliseconds value.
     *
     * @return the elapsedMilliseconds value
     */
    public long elapsedMilliseconds() {
        return this.elapsedMilliseconds;
    }

    /**
     * Set the elapsedMilliseconds value.
     *
     * @param elapsedMilliseconds the elapsedMilliseconds value to set
     * @return the FileTransferSearchResult object itself.
     */
    public FileTransferSearchResult withElapsedMilliseconds(long elapsedMilliseconds) {
        this.elapsedMilliseconds = elapsedMilliseconds;
        return this;
    }

}
