/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The InvalidChangeCommandFieldNotFoundException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("InvalidChangeCommandFieldNotFoundException")
public class InvalidChangeCommandFieldNotFoundException extends PictureparkValidationException {
    /**
     * The commandTypeName property.
     */
    @JsonProperty(value = "commandTypeName")
    private String commandTypeName;

    /**
     * The fieldId property.
     */
    @JsonProperty(value = "fieldId")
    private String fieldId;

    /**
     * The schemaId property.
     */
    @JsonProperty(value = "schemaId")
    private String schemaId;

    /**
     * Get the commandTypeName value.
     *
     * @return the commandTypeName value
     */
    public String commandTypeName() {
        return this.commandTypeName;
    }

    /**
     * Set the commandTypeName value.
     *
     * @param commandTypeName the commandTypeName value to set
     * @return the InvalidChangeCommandFieldNotFoundException object itself.
     */
    public InvalidChangeCommandFieldNotFoundException withCommandTypeName(String commandTypeName) {
        this.commandTypeName = commandTypeName;
        return this;
    }

    /**
     * Get the fieldId value.
     *
     * @return the fieldId value
     */
    public String fieldId() {
        return this.fieldId;
    }

    /**
     * Set the fieldId value.
     *
     * @param fieldId the fieldId value to set
     * @return the InvalidChangeCommandFieldNotFoundException object itself.
     */
    public InvalidChangeCommandFieldNotFoundException withFieldId(String fieldId) {
        this.fieldId = fieldId;
        return this;
    }

    /**
     * Get the schemaId value.
     *
     * @return the schemaId value
     */
    public String schemaId() {
        return this.schemaId;
    }

    /**
     * Set the schemaId value.
     *
     * @param schemaId the schemaId value to set
     * @return the InvalidChangeCommandFieldNotFoundException object itself.
     */
    public InvalidChangeCommandFieldNotFoundException withSchemaId(String schemaId) {
        this.schemaId = schemaId;
        return this;
    }

}
