/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The InvalidArgumentException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("InvalidArgumentException")
public class InvalidArgumentException extends PictureparkValidationException {
    /**
     * The argumentName property.
     */
    @JsonProperty(value = "argumentName")
    private String argumentName;

    /**
     * The argumentValue property.
     */
    @JsonProperty(value = "argumentValue")
    private String argumentValue;

    /**
     * Get the argumentName value.
     *
     * @return the argumentName value
     */
    public String argumentName() {
        return this.argumentName;
    }

    /**
     * Set the argumentName value.
     *
     * @param argumentName the argumentName value to set
     * @return the InvalidArgumentException object itself.
     */
    public InvalidArgumentException withArgumentName(String argumentName) {
        this.argumentName = argumentName;
        return this;
    }

    /**
     * Get the argumentValue value.
     *
     * @return the argumentValue value
     */
    public String argumentValue() {
        return this.argumentValue;
    }

    /**
     * Set the argumentValue value.
     *
     * @param argumentValue the argumentValue value to set
     * @return the InvalidArgumentException object itself.
     */
    public InvalidArgumentException withArgumentValue(String argumentValue) {
        this.argumentValue = argumentValue;
        return this;
    }

}
