/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LicenseeInfo model.
 */
public class LicenseeInfo {
    /**
     * The licenseeName property.
     */
    @JsonProperty(value = "licenseeName")
    private String licenseeName;

    /**
     * The licenseeID property.
     */
    @JsonProperty(value = "licenseeID")
    private String licenseeID;

    /**
     * Get the licenseeName value.
     *
     * @return the licenseeName value
     */
    public String licenseeName() {
        return this.licenseeName;
    }

    /**
     * Set the licenseeName value.
     *
     * @param licenseeName the licenseeName value to set
     * @return the LicenseeInfo object itself.
     */
    public LicenseeInfo withLicenseeName(String licenseeName) {
        this.licenseeName = licenseeName;
        return this;
    }

    /**
     * Get the licenseeID value.
     *
     * @return the licenseeID value
     */
    public String licenseeID() {
        return this.licenseeID;
    }

    /**
     * Set the licenseeID value.
     *
     * @param licenseeID the licenseeID value to set
     * @return the LicenseeInfo object itself.
     */
    public LicenseeInfo withLicenseeID(String licenseeID) {
        this.licenseeID = licenseeID;
        return this;
    }

}
