/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The OutputDetailImage model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("OutputDetailImage")
public class OutputDetailImage extends OutputDetailBase {
    /**
     * The width property.
     */
    @JsonProperty(value = "width", required = true)
    private int width;

    /**
     * The height property.
     */
    @JsonProperty(value = "height", required = true)
    private int height;

    /**
     * Get the width value.
     *
     * @return the width value
     */
    public int width() {
        return this.width;
    }

    /**
     * Set the width value.
     *
     * @param width the width value to set
     * @return the OutputDetailImage object itself.
     */
    public OutputDetailImage withWidth(int width) {
        this.width = width;
        return this;
    }

    /**
     * Get the height value.
     *
     * @return the height value
     */
    public int height() {
        return this.height;
    }

    /**
     * Set the height value.
     *
     * @param height the height value to set
     * @return the OutputDetailImage object itself.
     */
    public OutputDetailImage withHeight(int height) {
        this.height = height;
        return this;
    }

}
