/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The Output model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("Output")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "OutputDetail", value = OutputDetail.class)
})
public class Output {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The outputFormatId property.
     */
    @JsonProperty(value = "outputFormatId")
    private String outputFormatId;

    /**
     * The contentId property.
     */
    @JsonProperty(value = "contentId")
    private String contentId;

    /**
     * The detail property.
     */
    @JsonProperty(value = "detail")
    private OutputDetailBase detail;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Output object itself.
     */
    public Output withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the outputFormatId value.
     *
     * @return the outputFormatId value
     */
    public String outputFormatId() {
        return this.outputFormatId;
    }

    /**
     * Set the outputFormatId value.
     *
     * @param outputFormatId the outputFormatId value to set
     * @return the Output object itself.
     */
    public Output withOutputFormatId(String outputFormatId) {
        this.outputFormatId = outputFormatId;
        return this;
    }

    /**
     * Get the contentId value.
     *
     * @return the contentId value
     */
    public String contentId() {
        return this.contentId;
    }

    /**
     * Set the contentId value.
     *
     * @param contentId the contentId value to set
     * @return the Output object itself.
     */
    public Output withContentId(String contentId) {
        this.contentId = contentId;
        return this;
    }

    /**
     * Get the detail value.
     *
     * @return the detail value
     */
    public OutputDetailBase detail() {
        return this.detail;
    }

    /**
     * Set the detail value.
     *
     * @param detail the detail value to set
     * @return the Output object itself.
     */
    public Output withDetail(OutputDetailBase detail) {
        this.detail = detail;
        return this;
    }

}
