/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The PermissionValidationException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("PermissionValidationException")
public class PermissionValidationException extends PictureparkValidationException {
    /**
     * The permission property.
     */
    @JsonProperty(value = "permission")
    private String permission;

    /**
     * The operation property.
     */
    @JsonProperty(value = "operation")
    private String operation;

    /**
     * Get the permission value.
     *
     * @return the permission value
     */
    public String permission() {
        return this.permission;
    }

    /**
     * Set the permission value.
     *
     * @param permission the permission value to set
     * @return the PermissionValidationException object itself.
     */
    public PermissionValidationException withPermission(String permission) {
        this.permission = permission;
        return this;
    }

    /**
     * Get the operation value.
     *
     * @return the operation value
     */
    public String operation() {
        return this.operation;
    }

    /**
     * Set the operation value.
     *
     * @param operation the operation value to set
     * @return the PermissionValidationException object itself.
     */
    public PermissionValidationException withOperation(String operation) {
        this.operation = operation;
        return this;
    }

}
