/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The PictureparkNotFoundException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("PictureparkNotFoundException")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "ContentNotFoundException", value = ContentNotFoundException.class),
    @JsonSubTypes.Type(name = "DocumentVersionNotFoundException", value = DocumentVersionNotFoundException.class),
    @JsonSubTypes.Type(name = "ShareNotFoundException", value = ShareNotFoundException.class),
    @JsonSubTypes.Type(name = "ShareByTokenNotFoundException", value = ShareByTokenNotFoundException.class),
    @JsonSubTypes.Type(name = "OutputIdNotFoundException", value = OutputIdNotFoundException.class),
    @JsonSubTypes.Type(name = "DriveFileNotFoundException", value = DriveFileNotFoundException.class),
    @JsonSubTypes.Type(name = "OwnerTokenNotFoundException", value = OwnerTokenNotFoundException.class),
    @JsonSubTypes.Type(name = "PermissionSetNotFoundException", value = PermissionSetNotFoundException.class),
    @JsonSubTypes.Type(name = "ListItemNotFoundException", value = ListItemNotFoundException.class),
    @JsonSubTypes.Type(name = "TransferInfoNotFoundException", value = TransferInfoNotFoundException.class),
    @JsonSubTypes.Type(name = "FileTransferNotFoundException", value = FileTransferNotFoundException.class),
    @JsonSubTypes.Type(name = "TransferNotFoundException", value = TransferNotFoundException.class),
    @JsonSubTypes.Type(name = "SchemaInfoNotFoundException", value = SchemaInfoNotFoundException.class),
    @JsonSubTypes.Type(name = "SchemaNotFoundException", value = SchemaNotFoundException.class),
    @JsonSubTypes.Type(name = "ContentsNotFoundException", value = ContentsNotFoundException.class),
    @JsonSubTypes.Type(name = "BusinessProcessNotFoundException", value = BusinessProcessNotFoundException.class),
    @JsonSubTypes.Type(name = "BusinessProcessDefinitionNotFoundException", value = BusinessProcessDefinitionNotFoundException.class)
})
public class PictureparkNotFoundException extends PictureparkBusinessException {
    /**
     * The reference property.
     */
    @JsonProperty(value = "reference")
    private String reference;

    /**
     * Get the reference value.
     *
     * @return the reference value
     */
    public String reference() {
        return this.reference;
    }

    /**
     * Set the reference value.
     *
     * @param reference the reference value to set
     * @return the PictureparkNotFoundException object itself.
     */
    public PictureparkNotFoundException withReference(String reference) {
        this.reference = reference;
        return this;
    }

}
