/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The SchemaNotFoundInSearchIndexException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("SchemaNotFoundInSearchIndexException")
public class SchemaNotFoundInSearchIndexException extends PictureparkValidationException {
    /**
     * The searchIndexId property.
     */
    @JsonProperty(value = "searchIndexId")
    private String searchIndexId;

    /**
     * The schemaId property.
     */
    @JsonProperty(value = "schemaId")
    private String schemaId;

    /**
     * Get the searchIndexId value.
     *
     * @return the searchIndexId value
     */
    public String searchIndexId() {
        return this.searchIndexId;
    }

    /**
     * Set the searchIndexId value.
     *
     * @param searchIndexId the searchIndexId value to set
     * @return the SchemaNotFoundInSearchIndexException object itself.
     */
    public SchemaNotFoundInSearchIndexException withSearchIndexId(String searchIndexId) {
        this.searchIndexId = searchIndexId;
        return this;
    }

    /**
     * Get the schemaId value.
     *
     * @return the schemaId value
     */
    public String schemaId() {
        return this.schemaId;
    }

    /**
     * Set the schemaId value.
     *
     * @param schemaId the schemaId value to set
     * @return the SchemaNotFoundInSearchIndexException object itself.
     */
    public SchemaNotFoundInSearchIndexException withSchemaId(String schemaId) {
        this.schemaId = schemaId;
        return this;
    }

}
