/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The SchemaCyclicDependencyException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("SchemaCyclicDependencyException")
public class SchemaCyclicDependencyException extends PictureparkValidationException {
    /**
     * The schemaIds property.
     */
    @JsonProperty(value = "schemaIds")
    private List<String> schemaIds;

    /**
     * Get the schemaIds value.
     *
     * @return the schemaIds value
     */
    public List<String> schemaIds() {
        return this.schemaIds;
    }

    /**
     * Set the schemaIds value.
     *
     * @param schemaIds the schemaIds value to set
     * @return the SchemaCyclicDependencyException object itself.
     */
    public SchemaCyclicDependencyException withSchemaIds(List<String> schemaIds) {
        this.schemaIds = schemaIds;
        return this;
    }

}
