/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SchemaIndexingInfo model.
 */
public class SchemaIndexingInfo {
    /**
     * A collecction of indexing information for the fields of a schema.
     */
    @JsonProperty(value = "fields")
    private List<FieldIndexingInfo> fields;

    /**
     * Get the fields value.
     *
     * @return the fields value
     */
    public List<FieldIndexingInfo> fields() {
        return this.fields;
    }

    /**
     * Set the fields value.
     *
     * @param fields the fields value to set
     * @return the SchemaIndexingInfo object itself.
     */
    public SchemaIndexingInfo withFields(List<FieldIndexingInfo> fields) {
        this.fields = fields;
        return this;
    }

}
