/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Share model.
 */
public class Share {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The contentIds property.
     */
    @JsonProperty(value = "contentIds")
    private List<String> contentIds;

    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The audit property.
     */
    @JsonProperty(value = "audit")
    private UserAudit audit;

    /**
     * The expirationDate property.
     */
    @JsonProperty(value = "expirationDate")
    private DateTime expirationDate;

    /**
     * Possible values include: 'Basic', 'Embed'.
     */
    @JsonProperty(value = "shareType", required = true)
    private String shareType;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Share object itself.
     */
    public Share withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the contentIds value.
     *
     * @return the contentIds value
     */
    public List<String> contentIds() {
        return this.contentIds;
    }

    /**
     * Set the contentIds value.
     *
     * @param contentIds the contentIds value to set
     * @return the Share object itself.
     */
    public Share withContentIds(List<String> contentIds) {
        this.contentIds = contentIds;
        return this;
    }

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Share object itself.
     */
    public Share withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the audit value.
     *
     * @return the audit value
     */
    public UserAudit audit() {
        return this.audit;
    }

    /**
     * Set the audit value.
     *
     * @param audit the audit value to set
     * @return the Share object itself.
     */
    public Share withAudit(UserAudit audit) {
        this.audit = audit;
        return this;
    }

    /**
     * Get the expirationDate value.
     *
     * @return the expirationDate value
     */
    public DateTime expirationDate() {
        return this.expirationDate;
    }

    /**
     * Set the expirationDate value.
     *
     * @param expirationDate the expirationDate value to set
     * @return the Share object itself.
     */
    public Share withExpirationDate(DateTime expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * Get the shareType value.
     *
     * @return the shareType value
     */
    public String shareType() {
        return this.shareType;
    }

    /**
     * Set the shareType value.
     *
     * @param shareType the shareType value to set
     * @return the Share object itself.
     */
    public Share withShareType(String shareType) {
        this.shareType = shareType;
        return this;
    }

}
