/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ShareBasic model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ShareBasic")
public class ShareBasic extends ShareBase {
    /**
     * The mailRecipients property.
     */
    @JsonProperty(value = "mailRecipients")
    private List<MailRecipient> mailRecipients;

    /**
     * The internalRecipients property.
     */
    @JsonProperty(value = "internalRecipients")
    private List<InternalRecipient> internalRecipients;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Get the mailRecipients value.
     *
     * @return the mailRecipients value
     */
    public List<MailRecipient> mailRecipients() {
        return this.mailRecipients;
    }

    /**
     * Set the mailRecipients value.
     *
     * @param mailRecipients the mailRecipients value to set
     * @return the ShareBasic object itself.
     */
    public ShareBasic withMailRecipients(List<MailRecipient> mailRecipients) {
        this.mailRecipients = mailRecipients;
        return this;
    }

    /**
     * Get the internalRecipients value.
     *
     * @return the internalRecipients value
     */
    public List<InternalRecipient> internalRecipients() {
        return this.internalRecipients;
    }

    /**
     * Set the internalRecipients value.
     *
     * @param internalRecipients the internalRecipients value to set
     * @return the ShareBasic object itself.
     */
    public ShareBasic withInternalRecipients(List<InternalRecipient> internalRecipients) {
        this.internalRecipients = internalRecipients;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the ShareBasic object itself.
     */
    public ShareBasic withDescription(String description) {
        this.description = description;
        return this;
    }

}
