/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ShareDetail model.
 */
public class ShareDetail {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The creator property.
     */
    @JsonProperty(value = "creator")
    private ShareUser creator;

    /**
     * The audit property.
     */
    @JsonProperty(value = "audit")
    private UserAudit audit;

    /**
     * The contentSelections property.
     */
    @JsonProperty(value = "contentSelections")
    private List<ShareContentDetail> contentSelections;

    /**
     * The layerSchemaIds property.
     */
    @JsonProperty(value = "layerSchemaIds")
    private List<String> layerSchemaIds;

    /**
     * The data property.
     */
    @JsonProperty(value = "data")
    private ShareDataBase data;

    /**
     * The mailTemplateId property.
     */
    @JsonProperty(value = "mailTemplateId")
    private String mailTemplateId;

    /**
     * The expirationDate property.
     */
    @JsonProperty(value = "expirationDate")
    private DateTime expirationDate;

    /**
     * The template property.
     */
    @JsonProperty(value = "template")
    private TemplateBase template;

    /**
     * Possible values include: 'Full', 'Preview', 'None'.
     */
    @JsonProperty(value = "outputAccess", required = true)
    private String outputAccess;

    /**
     * Possible values include: 'Basic', 'Embed'.
     */
    @JsonProperty(value = "shareType", required = true)
    private String shareType;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the creator value.
     *
     * @return the creator value
     */
    public ShareUser creator() {
        return this.creator;
    }

    /**
     * Set the creator value.
     *
     * @param creator the creator value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withCreator(ShareUser creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Get the audit value.
     *
     * @return the audit value
     */
    public UserAudit audit() {
        return this.audit;
    }

    /**
     * Set the audit value.
     *
     * @param audit the audit value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withAudit(UserAudit audit) {
        this.audit = audit;
        return this;
    }

    /**
     * Get the contentSelections value.
     *
     * @return the contentSelections value
     */
    public List<ShareContentDetail> contentSelections() {
        return this.contentSelections;
    }

    /**
     * Set the contentSelections value.
     *
     * @param contentSelections the contentSelections value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withContentSelections(List<ShareContentDetail> contentSelections) {
        this.contentSelections = contentSelections;
        return this;
    }

    /**
     * Get the layerSchemaIds value.
     *
     * @return the layerSchemaIds value
     */
    public List<String> layerSchemaIds() {
        return this.layerSchemaIds;
    }

    /**
     * Set the layerSchemaIds value.
     *
     * @param layerSchemaIds the layerSchemaIds value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withLayerSchemaIds(List<String> layerSchemaIds) {
        this.layerSchemaIds = layerSchemaIds;
        return this;
    }

    /**
     * Get the data value.
     *
     * @return the data value
     */
    public ShareDataBase data() {
        return this.data;
    }

    /**
     * Set the data value.
     *
     * @param data the data value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withData(ShareDataBase data) {
        this.data = data;
        return this;
    }

    /**
     * Get the mailTemplateId value.
     *
     * @return the mailTemplateId value
     */
    public String mailTemplateId() {
        return this.mailTemplateId;
    }

    /**
     * Set the mailTemplateId value.
     *
     * @param mailTemplateId the mailTemplateId value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withMailTemplateId(String mailTemplateId) {
        this.mailTemplateId = mailTemplateId;
        return this;
    }

    /**
     * Get the expirationDate value.
     *
     * @return the expirationDate value
     */
    public DateTime expirationDate() {
        return this.expirationDate;
    }

    /**
     * Set the expirationDate value.
     *
     * @param expirationDate the expirationDate value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withExpirationDate(DateTime expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * Get the template value.
     *
     * @return the template value
     */
    public TemplateBase template() {
        return this.template;
    }

    /**
     * Set the template value.
     *
     * @param template the template value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withTemplate(TemplateBase template) {
        this.template = template;
        return this;
    }

    /**
     * Get the outputAccess value.
     *
     * @return the outputAccess value
     */
    public String outputAccess() {
        return this.outputAccess;
    }

    /**
     * Set the outputAccess value.
     *
     * @param outputAccess the outputAccess value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withOutputAccess(String outputAccess) {
        this.outputAccess = outputAccess;
        return this;
    }

    /**
     * Get the shareType value.
     *
     * @return the shareType value
     */
    public String shareType() {
        return this.shareType;
    }

    /**
     * Set the shareType value.
     *
     * @param shareType the shareType value to set
     * @return the ShareDetail object itself.
     */
    public ShareDetail withShareType(String shareType) {
        this.shareType = shareType;
        return this;
    }

}
