/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TimeCode model.
 */
public class TimeCode {
    /**
     * Possible values include: 'Timecode24', 'Timecode25', 'Timecode2997Drop',
     * 'Timecode2997NonDrop', 'Timecode30', 'Timecode50', 'Timecode5994Drop',
     * 'Timecode5994NonDrop', 'Timecode60', 'Timecode23976'.
     */
    @JsonProperty(value = "timeFormat")
    private String timeFormat;

    /**
     * The timeValue property.
     */
    @JsonProperty(value = "timeValue")
    private String timeValue;

    /**
     * Get the timeFormat value.
     *
     * @return the timeFormat value
     */
    public String timeFormat() {
        return this.timeFormat;
    }

    /**
     * Set the timeFormat value.
     *
     * @param timeFormat the timeFormat value to set
     * @return the TimeCode object itself.
     */
    public TimeCode withTimeFormat(String timeFormat) {
        this.timeFormat = timeFormat;
        return this;
    }

    /**
     * Get the timeValue value.
     *
     * @return the timeValue value
     */
    public String timeValue() {
        return this.timeValue;
    }

    /**
     * Set the timeValue value.
     *
     * @param timeValue the timeValue value to set
     * @return the TimeCode object itself.
     */
    public TimeCode withTimeValue(String timeValue) {
        this.timeValue = timeValue;
        return this;
    }

}
