/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TransferFile model.
 */
public class TransferFile {
    /**
     * The identifier property.
     */
    @JsonProperty(value = "identifier")
    private String identifier;

    /**
     * Get the identifier value.
     *
     * @return the identifier value
     */
    public String identifier() {
        return this.identifier;
    }

    /**
     * Set the identifier value.
     *
     * @param identifier the identifier value to set
     * @return the TransferFile object itself.
     */
    public TransferFile withIdentifier(String identifier) {
        this.identifier = identifier;
        return this;
    }

}
