/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TransferDetail model.
 */
public class TransferDetail {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The rev property.
     */
    @JsonProperty(value = "rev")
    private String rev;

    /**
     * The audit property.
     */
    @JsonProperty(value = "audit")
    private UserAudit audit;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Possible values include: 'Draft', 'UploadInProgress', 'UploadCompleted',
     * 'ImportInProgress', 'ImportCompleted', 'UploadCancelled',
     * 'ImportCancelled', 'ImportFailed', 'Created', 'Deleted',
     * 'TransferReady', 'FileDeleteInProgress', 'TransferCleanup'.
     */
    @JsonProperty(value = "state", required = true)
    private String state;

    /**
     * The businessProcessId property.
     */
    @JsonProperty(value = "businessProcessId")
    private String businessProcessId;

    /**
     * Possible values include: 'FileUpload', 'FileUploadAutoImport',
     * 'DriveImport', 'DriveExport', 'WebDownload', 'SchemaImport'.
     */
    @JsonProperty(value = "transferType", required = true)
    private String transferType;

    /**
     * The itemProgress property.
     */
    @JsonProperty(value = "itemProgress", required = true)
    private long itemProgress;

    /**
     * The itemCount property.
     */
    @JsonProperty(value = "itemCount", required = true)
    private long itemCount;

    /**
     * The itemsFailed property.
     */
    @JsonProperty(value = "itemsFailed", required = true)
    private long itemsFailed;

    /**
     * The itemsCancelled property.
     */
    @JsonProperty(value = "itemsCancelled", required = true)
    private long itemsCancelled;

    /**
     * The lastProgressStamp property.
     */
    @JsonProperty(value = "lastProgressStamp", required = true)
    private long lastProgressStamp;

    /**
     * The fileTransferCount property.
     */
    @JsonProperty(value = "fileTransferCount", required = true)
    private long fileTransferCount;

    /**
     * The collectionId property.
     */
    @JsonProperty(value = "collectionId")
    private String collectionId;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the rev value.
     *
     * @return the rev value
     */
    public String rev() {
        return this.rev;
    }

    /**
     * Set the rev value.
     *
     * @param rev the rev value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withRev(String rev) {
        this.rev = rev;
        return this;
    }

    /**
     * Get the audit value.
     *
     * @return the audit value
     */
    public UserAudit audit() {
        return this.audit;
    }

    /**
     * Set the audit value.
     *
     * @param audit the audit value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withAudit(UserAudit audit) {
        this.audit = audit;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the businessProcessId value.
     *
     * @return the businessProcessId value
     */
    public String businessProcessId() {
        return this.businessProcessId;
    }

    /**
     * Set the businessProcessId value.
     *
     * @param businessProcessId the businessProcessId value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withBusinessProcessId(String businessProcessId) {
        this.businessProcessId = businessProcessId;
        return this;
    }

    /**
     * Get the transferType value.
     *
     * @return the transferType value
     */
    public String transferType() {
        return this.transferType;
    }

    /**
     * Set the transferType value.
     *
     * @param transferType the transferType value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withTransferType(String transferType) {
        this.transferType = transferType;
        return this;
    }

    /**
     * Get the itemProgress value.
     *
     * @return the itemProgress value
     */
    public long itemProgress() {
        return this.itemProgress;
    }

    /**
     * Set the itemProgress value.
     *
     * @param itemProgress the itemProgress value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withItemProgress(long itemProgress) {
        this.itemProgress = itemProgress;
        return this;
    }

    /**
     * Get the itemCount value.
     *
     * @return the itemCount value
     */
    public long itemCount() {
        return this.itemCount;
    }

    /**
     * Set the itemCount value.
     *
     * @param itemCount the itemCount value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withItemCount(long itemCount) {
        this.itemCount = itemCount;
        return this;
    }

    /**
     * Get the itemsFailed value.
     *
     * @return the itemsFailed value
     */
    public long itemsFailed() {
        return this.itemsFailed;
    }

    /**
     * Set the itemsFailed value.
     *
     * @param itemsFailed the itemsFailed value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withItemsFailed(long itemsFailed) {
        this.itemsFailed = itemsFailed;
        return this;
    }

    /**
     * Get the itemsCancelled value.
     *
     * @return the itemsCancelled value
     */
    public long itemsCancelled() {
        return this.itemsCancelled;
    }

    /**
     * Set the itemsCancelled value.
     *
     * @param itemsCancelled the itemsCancelled value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withItemsCancelled(long itemsCancelled) {
        this.itemsCancelled = itemsCancelled;
        return this;
    }

    /**
     * Get the lastProgressStamp value.
     *
     * @return the lastProgressStamp value
     */
    public long lastProgressStamp() {
        return this.lastProgressStamp;
    }

    /**
     * Set the lastProgressStamp value.
     *
     * @param lastProgressStamp the lastProgressStamp value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withLastProgressStamp(long lastProgressStamp) {
        this.lastProgressStamp = lastProgressStamp;
        return this;
    }

    /**
     * Get the fileTransferCount value.
     *
     * @return the fileTransferCount value
     */
    public long fileTransferCount() {
        return this.fileTransferCount;
    }

    /**
     * Set the fileTransferCount value.
     *
     * @param fileTransferCount the fileTransferCount value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withFileTransferCount(long fileTransferCount) {
        this.fileTransferCount = fileTransferCount;
        return this;
    }

    /**
     * Get the collectionId value.
     *
     * @return the collectionId value
     */
    public String collectionId() {
        return this.collectionId;
    }

    /**
     * Set the collectionId value.
     *
     * @param collectionId the collectionId value to set
     * @return the TransferDetail object itself.
     */
    public TransferDetail withCollectionId(String collectionId) {
        this.collectionId = collectionId;
        return this;
    }

}
