/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The UnsupportedListItemChangeCommandException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("UnsupportedListItemChangeCommandException")
public class UnsupportedListItemChangeCommandException extends PictureparkValidationException {
    /**
     * The commandType property.
     */
    @JsonProperty(value = "commandType")
    private String commandType;

    /**
     * Get the commandType value.
     *
     * @return the commandType value
     */
    public String commandType() {
        return this.commandType;
    }

    /**
     * Set the commandType value.
     *
     * @param commandType the commandType value to set
     * @return the UnsupportedListItemChangeCommandException object itself.
     */
    public UnsupportedListItemChangeCommandException withCommandType(String commandType) {
        this.commandType = commandType;
        return this;
    }

}
