/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The UserNotFoundException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("UserNotFoundException")
public class UserNotFoundException extends PictureparkBusinessException {
    /**
     * The missingUserId property.
     */
    @JsonProperty(value = "missingUserId")
    private String missingUserId;

    /**
     * Get the missingUserId value.
     *
     * @return the missingUserId value
     */
    public String missingUserId() {
        return this.missingUserId;
    }

    /**
     * Set the missingUserId value.
     *
     * @param missingUserId the missingUserId value to set
     * @return the UserNotFoundException object itself.
     */
    public UserNotFoundException withMissingUserId(String missingUserId) {
        this.missingUserId = missingUserId;
        return this;
    }

}
