/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The VersionInfo2 model.
 */
public class VersionInfo2 {
    /**
     * The comments property.
     */
    @JsonProperty(value = "comments")
    private String comments;

    /**
     * The event property.
     */
    @JsonProperty(value = "event")
    private Event event;

    /**
     * The modifier property.
     */
    @JsonProperty(value = "modifier")
    private String modifier;

    /**
     * The modifyDate property.
     */
    @JsonProperty(value = "modifyDate")
    private DateTime modifyDate;

    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private String version;

    /**
     * Get the comments value.
     *
     * @return the comments value
     */
    public String comments() {
        return this.comments;
    }

    /**
     * Set the comments value.
     *
     * @param comments the comments value to set
     * @return the VersionInfo2 object itself.
     */
    public VersionInfo2 withComments(String comments) {
        this.comments = comments;
        return this;
    }

    /**
     * Get the event value.
     *
     * @return the event value
     */
    public Event event() {
        return this.event;
    }

    /**
     * Set the event value.
     *
     * @param event the event value to set
     * @return the VersionInfo2 object itself.
     */
    public VersionInfo2 withEvent(Event event) {
        this.event = event;
        return this;
    }

    /**
     * Get the modifier value.
     *
     * @return the modifier value
     */
    public String modifier() {
        return this.modifier;
    }

    /**
     * Set the modifier value.
     *
     * @param modifier the modifier value to set
     * @return the VersionInfo2 object itself.
     */
    public VersionInfo2 withModifier(String modifier) {
        this.modifier = modifier;
        return this;
    }

    /**
     * Get the modifyDate value.
     *
     * @return the modifyDate value
     */
    public DateTime modifyDate() {
        return this.modifyDate;
    }

    /**
     * Set the modifyDate value.
     *
     * @param modifyDate the modifyDate value to set
     * @return the VersionInfo2 object itself.
     */
    public VersionInfo2 withModifyDate(DateTime modifyDate) {
        this.modifyDate = modifyDate;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public String version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the VersionInfo2 object itself.
     */
    public VersionInfo2 withVersion(String version) {
        this.version = version;
        return this;
    }

}
