/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The WrongChunkSizeException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("WrongChunkSizeException")
public class WrongChunkSizeException extends PictureparkValidationException {
    /**
     * The actual property.
     */
    @JsonProperty(value = "actual", required = true)
    private long actual;

    /**
     * The expected property.
     */
    @JsonProperty(value = "expected", required = true)
    private long expected;

    /**
     * Get the actual value.
     *
     * @return the actual value
     */
    public long actual() {
        return this.actual;
    }

    /**
     * Set the actual value.
     *
     * @param actual the actual value to set
     * @return the WrongChunkSizeException object itself.
     */
    public WrongChunkSizeException withActual(long actual) {
        this.actual = actual;
        return this;
    }

    /**
     * Get the expected value.
     *
     * @return the expected value
     */
    public long expected() {
        return this.expected;
    }

    /**
     * Set the expected value.
     *
     * @param expected the expected value to set
     * @return the WrongChunkSizeException object itself.
     */
    public WrongChunkSizeException withExpected(long expected) {
        this.expected = expected;
        return this;
    }

}
