/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Channel model.
 */
public class Channel {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The sortOrder property.
     */
    @JsonProperty(value = "sortOrder", required = true)
    private int sortOrder;

    /**
     * The search index id.
     */
    @JsonProperty(value = "searchIndexId")
    private String searchIndexId;

    /**
     * Possible values include: 'Content', 'BasicShare', 'EmbedShare',
     * 'Metadata', 'FileTransfer'.
     */
    @JsonProperty(value = "entityType", required = true)
    private String entityType;

    /**
     * An id list of schemas with schema type content whose content documents
     * should be found by the simple search.
     * The search by filters and aggregations are unaffected.
     */
    @JsonProperty(value = "schemaIds")
    private List<String> schemaIds;

    /**
     * An optional search filter. Limits the content document result set on
     * each search and aggregation request.
     */
    @JsonProperty(value = "filter")
    private FilterBase filter;

    /**
     * Language specific names.
     */
    @JsonProperty(value = "names")
    private Object names;

    /**
     * The sort property.
     */
    @JsonProperty(value = "sort")
    private List<SortInfo> sort;

    /**
     * An optional list of aggregators. These aggregations are added by default
     * on each aggregation requests.
     */
    @JsonProperty(value = "aggregations")
    private List<AggregatorBase> aggregations;

    /**
     * An Optional list of fields. These fields extend the list of simple
     * search fields outside the bounds of any schema field configuration.
     */
    @JsonProperty(value = "extendedSimpleSearchFields")
    private List<String> extendedSimpleSearchFields;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Channel object itself.
     */
    public Channel withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the sortOrder value.
     *
     * @return the sortOrder value
     */
    public int sortOrder() {
        return this.sortOrder;
    }

    /**
     * Set the sortOrder value.
     *
     * @param sortOrder the sortOrder value to set
     * @return the Channel object itself.
     */
    public Channel withSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }

    /**
     * Get the searchIndexId value.
     *
     * @return the searchIndexId value
     */
    public String searchIndexId() {
        return this.searchIndexId;
    }

    /**
     * Set the searchIndexId value.
     *
     * @param searchIndexId the searchIndexId value to set
     * @return the Channel object itself.
     */
    public Channel withSearchIndexId(String searchIndexId) {
        this.searchIndexId = searchIndexId;
        return this;
    }

    /**
     * Get the entityType value.
     *
     * @return the entityType value
     */
    public String entityType() {
        return this.entityType;
    }

    /**
     * Set the entityType value.
     *
     * @param entityType the entityType value to set
     * @return the Channel object itself.
     */
    public Channel withEntityType(String entityType) {
        this.entityType = entityType;
        return this;
    }

    /**
     * Get the schemaIds value.
     *
     * @return the schemaIds value
     */
    public List<String> schemaIds() {
        return this.schemaIds;
    }

    /**
     * Set the schemaIds value.
     *
     * @param schemaIds the schemaIds value to set
     * @return the Channel object itself.
     */
    public Channel withSchemaIds(List<String> schemaIds) {
        this.schemaIds = schemaIds;
        return this;
    }

    /**
     * Get the filter value.
     *
     * @return the filter value
     */
    public FilterBase filter() {
        return this.filter;
    }

    /**
     * Set the filter value.
     *
     * @param filter the filter value to set
     * @return the Channel object itself.
     */
    public Channel withFilter(FilterBase filter) {
        this.filter = filter;
        return this;
    }

    /**
     * Get the names value.
     *
     * @return the names value
     */
    public Object names() {
        return this.names;
    }

    /**
     * Set the names value.
     *
     * @param names the names value to set
     * @return the Channel object itself.
     */
    public Channel withNames(Object names) {
        this.names = names;
        return this;
    }

    /**
     * Get the sort value.
     *
     * @return the sort value
     */
    public List<SortInfo> sort() {
        return this.sort;
    }

    /**
     * Set the sort value.
     *
     * @param sort the sort value to set
     * @return the Channel object itself.
     */
    public Channel withSort(List<SortInfo> sort) {
        this.sort = sort;
        return this;
    }

    /**
     * Get the aggregations value.
     *
     * @return the aggregations value
     */
    public List<AggregatorBase> aggregations() {
        return this.aggregations;
    }

    /**
     * Set the aggregations value.
     *
     * @param aggregations the aggregations value to set
     * @return the Channel object itself.
     */
    public Channel withAggregations(List<AggregatorBase> aggregations) {
        this.aggregations = aggregations;
        return this;
    }

    /**
     * Get the extendedSimpleSearchFields value.
     *
     * @return the extendedSimpleSearchFields value
     */
    public List<String> extendedSimpleSearchFields() {
        return this.extendedSimpleSearchFields;
    }

    /**
     * Set the extendedSimpleSearchFields value.
     *
     * @param extendedSimpleSearchFields the extendedSimpleSearchFields value to set
     * @return the Channel object itself.
     */
    public Channel withExtendedSimpleSearchFields(List<String> extendedSimpleSearchFields) {
        this.extendedSimpleSearchFields = extendedSimpleSearchFields;
        return this;
    }

}
