/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The GeoBoundingBoxFilter returns documents that are found based on a point
 * location using a bounding box.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("GeoBoundingBoxFilter")
public class GeoBoundingBoxFilter extends FilterBase {
    /**
     * The elastic search index field to execute the filter on.
     */
    @JsonProperty(value = "field")
    private String field;

    /**
     * The top left longitude/latitude configuration.
     */
    @JsonProperty(value = "topLeft")
    private GeoLocation topLeft;

    /**
     * The bottom right longitude/latitude configuration.
     */
    @JsonProperty(value = "bottomRight")
    private GeoLocation bottomRight;

    /**
     * Get the field value.
     *
     * @return the field value
     */
    public String field() {
        return this.field;
    }

    /**
     * Set the field value.
     *
     * @param field the field value to set
     * @return the GeoBoundingBoxFilter object itself.
     */
    public GeoBoundingBoxFilter withField(String field) {
        this.field = field;
        return this;
    }

    /**
     * Get the topLeft value.
     *
     * @return the topLeft value
     */
    public GeoLocation topLeft() {
        return this.topLeft;
    }

    /**
     * Set the topLeft value.
     *
     * @param topLeft the topLeft value to set
     * @return the GeoBoundingBoxFilter object itself.
     */
    public GeoBoundingBoxFilter withTopLeft(GeoLocation topLeft) {
        this.topLeft = topLeft;
        return this;
    }

    /**
     * Get the bottomRight value.
     *
     * @return the bottomRight value
     */
    public GeoLocation bottomRight() {
        return this.bottomRight;
    }

    /**
     * Set the bottomRight value.
     *
     * @param bottomRight the bottomRight value to set
     * @return the GeoBoundingBoxFilter object itself.
     */
    public GeoBoundingBoxFilter withBottomRight(GeoLocation bottomRight) {
        this.bottomRight = bottomRight;
        return this;
    }

}
