/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LiveStreamSearchRequest model.
 */
public class LiveStreamSearchRequest {
    /**
     * The from property.
     */
    @JsonProperty(value = "from", required = true)
    private DateTime from;

    /**
     * The to property.
     */
    @JsonProperty(value = "to", required = true)
    private DateTime to;

    /**
     * The start property.
     */
    @JsonProperty(value = "start", required = true)
    private int start;

    /**
     * The limit property.
     */
    @JsonProperty(value = "limit", required = true)
    private int limit;

    /**
     * The pageToken property.
     */
    @JsonProperty(value = "pageToken")
    private String pageToken;

    /**
     * Get the from value.
     *
     * @return the from value
     */
    public DateTime from() {
        return this.from;
    }

    /**
     * Set the from value.
     *
     * @param from the from value to set
     * @return the LiveStreamSearchRequest object itself.
     */
    public LiveStreamSearchRequest withFrom(DateTime from) {
        this.from = from;
        return this;
    }

    /**
     * Get the to value.
     *
     * @return the to value
     */
    public DateTime to() {
        return this.to;
    }

    /**
     * Set the to value.
     *
     * @param to the to value to set
     * @return the LiveStreamSearchRequest object itself.
     */
    public LiveStreamSearchRequest withTo(DateTime to) {
        this.to = to;
        return this;
    }

    /**
     * Get the start value.
     *
     * @return the start value
     */
    public int start() {
        return this.start;
    }

    /**
     * Set the start value.
     *
     * @param start the start value to set
     * @return the LiveStreamSearchRequest object itself.
     */
    public LiveStreamSearchRequest withStart(int start) {
        this.start = start;
        return this;
    }

    /**
     * Get the limit value.
     *
     * @return the limit value
     */
    public int limit() {
        return this.limit;
    }

    /**
     * Set the limit value.
     *
     * @param limit the limit value to set
     * @return the LiveStreamSearchRequest object itself.
     */
    public LiveStreamSearchRequest withLimit(int limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get the pageToken value.
     *
     * @return the pageToken value
     */
    public String pageToken() {
        return this.pageToken;
    }

    /**
     * Set the pageToken value.
     *
     * @param pageToken the pageToken value to set
     * @return the LiveStreamSearchRequest object itself.
     */
    public LiveStreamSearchRequest withPageToken(String pageToken) {
        this.pageToken = pageToken;
        return this;
    }

}
