/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ObjectStoreResponseException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ObjectStoreResponseException")
public class ObjectStoreResponseException extends PictureparkBusinessException {
    /**
     * The rowErrorMessages property.
     */
    @JsonProperty(value = "rowErrorMessages")
    private String rowErrorMessages;

    /**
     * Get the rowErrorMessages value.
     *
     * @return the rowErrorMessages value
     */
    public String rowErrorMessages() {
        return this.rowErrorMessages;
    }

    /**
     * Set the rowErrorMessages value.
     *
     * @param rowErrorMessages the rowErrorMessages value to set
     * @return the ObjectStoreResponseException object itself.
     */
    public ObjectStoreResponseException withRowErrorMessages(String rowErrorMessages) {
        this.rowErrorMessages = rowErrorMessages;
        return this;
    }

}
