/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ShareBasicDetail model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ShareBasicDetail")
public class ShareBasicDetail extends ShareBaseDetail {
    /**
     * The url property.
     */
    @JsonProperty(value = "url")
    private String url;

    /**
     * The mailRecipients property.
     */
    @JsonProperty(value = "mailRecipients")
    private List<MailRecipient> mailRecipients;

    /**
     * The internalRecipients property.
     */
    @JsonProperty(value = "internalRecipients")
    private List<InternalRecipient> internalRecipients;

    /**
     * The languageCode property.
     */
    @JsonProperty(value = "languageCode")
    private String languageCode;

    /**
     * Get the url value.
     *
     * @return the url value
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the url value.
     *
     * @param url the url value to set
     * @return the ShareBasicDetail object itself.
     */
    public ShareBasicDetail withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get the mailRecipients value.
     *
     * @return the mailRecipients value
     */
    public List<MailRecipient> mailRecipients() {
        return this.mailRecipients;
    }

    /**
     * Set the mailRecipients value.
     *
     * @param mailRecipients the mailRecipients value to set
     * @return the ShareBasicDetail object itself.
     */
    public ShareBasicDetail withMailRecipients(List<MailRecipient> mailRecipients) {
        this.mailRecipients = mailRecipients;
        return this;
    }

    /**
     * Get the internalRecipients value.
     *
     * @return the internalRecipients value
     */
    public List<InternalRecipient> internalRecipients() {
        return this.internalRecipients;
    }

    /**
     * Set the internalRecipients value.
     *
     * @param internalRecipients the internalRecipients value to set
     * @return the ShareBasicDetail object itself.
     */
    public ShareBasicDetail withInternalRecipients(List<InternalRecipient> internalRecipients) {
        this.internalRecipients = internalRecipients;
        return this;
    }

    /**
     * Get the languageCode value.
     *
     * @return the languageCode value
     */
    public String languageCode() {
        return this.languageCode;
    }

    /**
     * Set the languageCode value.
     *
     * @param languageCode the languageCode value to set
     * @return the ShareBasicDetail object itself.
     */
    public ShareBasicDetail withLanguageCode(String languageCode) {
        this.languageCode = languageCode;
        return this;
    }

}
