/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The StorageCausedBy model.
 */
public class StorageCausedBy {
    /**
     * The reason property.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * The type property.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * The innerCausedBy property.
     */
    @JsonProperty(value = "innerCausedBy")
    private StorageCausedBy innerCausedBy;

    /**
     * Get the reason value.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason value.
     *
     * @param reason the reason value to set
     * @return the StorageCausedBy object itself.
     */
    public StorageCausedBy withReason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the type value.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type value.
     *
     * @param type the type value to set
     * @return the StorageCausedBy object itself.
     */
    public StorageCausedBy withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the innerCausedBy value.
     *
     * @return the innerCausedBy value
     */
    public StorageCausedBy innerCausedBy() {
        return this.innerCausedBy;
    }

    /**
     * Set the innerCausedBy value.
     *
     * @param innerCausedBy the innerCausedBy value to set
     * @return the StorageCausedBy object itself.
     */
    public StorageCausedBy withInnerCausedBy(StorageCausedBy innerCausedBy) {
        this.innerCausedBy = innerCausedBy;
        return this;
    }

}
