/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TransferUploadFile model.
 */
public class TransferUploadFile extends TransferFile {
    /**
     * The fileName property.
     */
    @JsonProperty(value = "fileName")
    private String fileName;

    /**
     * Get the fileName value.
     *
     * @return the fileName value
     */
    public String fileName() {
        return this.fileName;
    }

    /**
     * Set the fileName value.
     *
     * @param fileName the fileName value to set
     * @return the TransferUploadFile object itself.
     */
    public TransferUploadFile withFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

}
