/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The XmpMM model.
 */
public class XmpMM {
    /**
     * The derivedFrom property.
     */
    @JsonProperty(value = "derivedFrom")
    private Reference derivedFrom;

    /**
     * The documentID property.
     */
    @JsonProperty(value = "documentID")
    private String documentID;

    /**
     * The history property.
     */
    @JsonProperty(value = "history")
    private List<Event> history;

    /**
     * The ingredients property.
     */
    @JsonProperty(value = "ingredients")
    private List<Reference> ingredients;

    /**
     * The instanceID property.
     */
    @JsonProperty(value = "instanceID")
    private String instanceID;

    /**
     * The managedFrom property.
     */
    @JsonProperty(value = "managedFrom")
    private Reference managedFrom;

    /**
     * The manager property.
     */
    @JsonProperty(value = "manager")
    private String manager;

    /**
     * The manageTo property.
     */
    @JsonProperty(value = "manageTo")
    private String manageTo;

    /**
     * The manageUI property.
     */
    @JsonProperty(value = "manageUI")
    private String manageUI;

    /**
     * The managerVariant property.
     */
    @JsonProperty(value = "managerVariant")
    private String managerVariant;

    /**
     * The originalDocumentID property.
     */
    @JsonProperty(value = "originalDocumentID")
    private String originalDocumentID;

    /**
     * The renditionClass property.
     */
    @JsonProperty(value = "renditionClass")
    private String renditionClass;

    /**
     * The renditionParams property.
     */
    @JsonProperty(value = "renditionParams")
    private String renditionParams;

    /**
     * The versionID property.
     */
    @JsonProperty(value = "versionID")
    private String versionID;

    /**
     * The versions property.
     */
    @JsonProperty(value = "versions")
    private List<VersionInfo> versions;

    /**
     * Get the derivedFrom value.
     *
     * @return the derivedFrom value
     */
    public Reference derivedFrom() {
        return this.derivedFrom;
    }

    /**
     * Set the derivedFrom value.
     *
     * @param derivedFrom the derivedFrom value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withDerivedFrom(Reference derivedFrom) {
        this.derivedFrom = derivedFrom;
        return this;
    }

    /**
     * Get the documentID value.
     *
     * @return the documentID value
     */
    public String documentID() {
        return this.documentID;
    }

    /**
     * Set the documentID value.
     *
     * @param documentID the documentID value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withDocumentID(String documentID) {
        this.documentID = documentID;
        return this;
    }

    /**
     * Get the history value.
     *
     * @return the history value
     */
    public List<Event> history() {
        return this.history;
    }

    /**
     * Set the history value.
     *
     * @param history the history value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withHistory(List<Event> history) {
        this.history = history;
        return this;
    }

    /**
     * Get the ingredients value.
     *
     * @return the ingredients value
     */
    public List<Reference> ingredients() {
        return this.ingredients;
    }

    /**
     * Set the ingredients value.
     *
     * @param ingredients the ingredients value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withIngredients(List<Reference> ingredients) {
        this.ingredients = ingredients;
        return this;
    }

    /**
     * Get the instanceID value.
     *
     * @return the instanceID value
     */
    public String instanceID() {
        return this.instanceID;
    }

    /**
     * Set the instanceID value.
     *
     * @param instanceID the instanceID value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withInstanceID(String instanceID) {
        this.instanceID = instanceID;
        return this;
    }

    /**
     * Get the managedFrom value.
     *
     * @return the managedFrom value
     */
    public Reference managedFrom() {
        return this.managedFrom;
    }

    /**
     * Set the managedFrom value.
     *
     * @param managedFrom the managedFrom value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withManagedFrom(Reference managedFrom) {
        this.managedFrom = managedFrom;
        return this;
    }

    /**
     * Get the manager value.
     *
     * @return the manager value
     */
    public String manager() {
        return this.manager;
    }

    /**
     * Set the manager value.
     *
     * @param manager the manager value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withManager(String manager) {
        this.manager = manager;
        return this;
    }

    /**
     * Get the manageTo value.
     *
     * @return the manageTo value
     */
    public String manageTo() {
        return this.manageTo;
    }

    /**
     * Set the manageTo value.
     *
     * @param manageTo the manageTo value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withManageTo(String manageTo) {
        this.manageTo = manageTo;
        return this;
    }

    /**
     * Get the manageUI value.
     *
     * @return the manageUI value
     */
    public String manageUI() {
        return this.manageUI;
    }

    /**
     * Set the manageUI value.
     *
     * @param manageUI the manageUI value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withManageUI(String manageUI) {
        this.manageUI = manageUI;
        return this;
    }

    /**
     * Get the managerVariant value.
     *
     * @return the managerVariant value
     */
    public String managerVariant() {
        return this.managerVariant;
    }

    /**
     * Set the managerVariant value.
     *
     * @param managerVariant the managerVariant value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withManagerVariant(String managerVariant) {
        this.managerVariant = managerVariant;
        return this;
    }

    /**
     * Get the originalDocumentID value.
     *
     * @return the originalDocumentID value
     */
    public String originalDocumentID() {
        return this.originalDocumentID;
    }

    /**
     * Set the originalDocumentID value.
     *
     * @param originalDocumentID the originalDocumentID value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withOriginalDocumentID(String originalDocumentID) {
        this.originalDocumentID = originalDocumentID;
        return this;
    }

    /**
     * Get the renditionClass value.
     *
     * @return the renditionClass value
     */
    public String renditionClass() {
        return this.renditionClass;
    }

    /**
     * Set the renditionClass value.
     *
     * @param renditionClass the renditionClass value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withRenditionClass(String renditionClass) {
        this.renditionClass = renditionClass;
        return this;
    }

    /**
     * Get the renditionParams value.
     *
     * @return the renditionParams value
     */
    public String renditionParams() {
        return this.renditionParams;
    }

    /**
     * Set the renditionParams value.
     *
     * @param renditionParams the renditionParams value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withRenditionParams(String renditionParams) {
        this.renditionParams = renditionParams;
        return this;
    }

    /**
     * Get the versionID value.
     *
     * @return the versionID value
     */
    public String versionID() {
        return this.versionID;
    }

    /**
     * Set the versionID value.
     *
     * @param versionID the versionID value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withVersionID(String versionID) {
        this.versionID = versionID;
        return this;
    }

    /**
     * Get the versions value.
     *
     * @return the versions value
     */
    public List<VersionInfo> versions() {
        return this.versions;
    }

    /**
     * Set the versions value.
     *
     * @param versions the versions value to set
     * @return the XmpMM object itself.
     */
    public XmpMM withVersions(List<VersionInfo> versions) {
        this.versions = versions;
        return this;
    }

}
