/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The XmpNote model.
 */
public class XmpNote {
    /**
     * The hasExtendedXMP property.
     */
    @JsonProperty(value = "hasExtendedXMP")
    private String hasExtendedXMP;

    /**
     * Get the hasExtendedXMP value.
     *
     * @return the hasExtendedXMP value
     */
    public String hasExtendedXMP() {
        return this.hasExtendedXMP;
    }

    /**
     * Set the hasExtendedXMP value.
     *
     * @param hasExtendedXMP the hasExtendedXMP value to set
     * @return the XmpNote object itself.
     */
    public XmpNote withHasExtendedXMP(String hasExtendedXMP) {
        this.hasExtendedXMP = hasExtendedXMP;
        return this;
    }

}
