/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package picturepark.models;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The XmpRights model.
 */
public class XmpRights {
    /**
     * The certificate property.
     */
    @JsonProperty(value = "certificate")
    private String certificate;

    /**
     * The marked property.
     */
    @JsonProperty(value = "marked")
    private Boolean marked;

    /**
     * The owner property.
     */
    @JsonProperty(value = "owner")
    private List<String> owner;

    /**
     * The usageTerms property.
     */
    @JsonProperty(value = "usageTerms")
    private Map<String, String> usageTerms;

    /**
     * The webStatement property.
     */
    @JsonProperty(value = "webStatement")
    private String webStatement;

    /**
     * Get the certificate value.
     *
     * @return the certificate value
     */
    public String certificate() {
        return this.certificate;
    }

    /**
     * Set the certificate value.
     *
     * @param certificate the certificate value to set
     * @return the XmpRights object itself.
     */
    public XmpRights withCertificate(String certificate) {
        this.certificate = certificate;
        return this;
    }

    /**
     * Get the marked value.
     *
     * @return the marked value
     */
    public Boolean marked() {
        return this.marked;
    }

    /**
     * Set the marked value.
     *
     * @param marked the marked value to set
     * @return the XmpRights object itself.
     */
    public XmpRights withMarked(Boolean marked) {
        this.marked = marked;
        return this;
    }

    /**
     * Get the owner value.
     *
     * @return the owner value
     */
    public List<String> owner() {
        return this.owner;
    }

    /**
     * Set the owner value.
     *
     * @param owner the owner value to set
     * @return the XmpRights object itself.
     */
    public XmpRights withOwner(List<String> owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get the usageTerms value.
     *
     * @return the usageTerms value
     */
    public Map<String, String> usageTerms() {
        return this.usageTerms;
    }

    /**
     * Set the usageTerms value.
     *
     * @param usageTerms the usageTerms value to set
     * @return the XmpRights object itself.
     */
    public XmpRights withUsageTerms(Map<String, String> usageTerms) {
        this.usageTerms = usageTerms;
        return this;
    }

    /**
     * Get the webStatement value.
     *
     * @return the webStatement value
     */
    public String webStatement() {
        return this.webStatement;
    }

    /**
     * Set the webStatement value.
     *
     * @param webStatement the webStatement value to set
     * @return the XmpRights object itself.
     */
    public XmpRights withWebStatement(String webStatement) {
        this.webStatement = webStatement;
        return this;
    }

}
