/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.implementation;

import retrofit2.Retrofit;
import foobar.JsonSchemas;
import com.google.common.reflect.TypeToken;
import com.microsoft.rest.RestException;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import foobar.models.PictureparkException;
import java.io.IOException;
import okhttp3.ResponseBody;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.Path;
import retrofit2.Response;
import rx.functions.Func1;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in JsonSchemas.
 */
public class JsonSchemasImpl implements JsonSchemas {
    /** The Retrofit service to perform REST calls. */
    private JsonSchemasService service;
    /** The service client containing this operation class. */
    private WebAPISwaggerspecificationImpl client;

    /**
     * Initializes an instance of JsonSchemas.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public JsonSchemasImpl(Retrofit retrofit, WebAPISwaggerspecificationImpl client) {
        this.service = retrofit.create(JsonSchemasService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for JsonSchemas to be
     * used by Retrofit to perform actually REST calls.
     */
    interface JsonSchemasService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: foobar.JsonSchemas get" })
        @GET("V1/JsonSchemas/{SchemaId}")
        Observable<Response<ResponseBody>> get(@Path("SchemaId") String schemaId);

    }

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Object object if successful.
     */
    public Object get(String schemaId) {
        return getWithServiceResponseAsync(schemaId).toBlocking().single().body();
    }

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<Object> getAsync(String schemaId, final ServiceCallback<Object> serviceCallback) {
        return ServiceFuture.fromResponse(getWithServiceResponseAsync(schemaId), serviceCallback);
    }

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Object object
     */
    public Observable<Object> getAsync(String schemaId) {
        return getWithServiceResponseAsync(schemaId).map(new Func1<ServiceResponse<Object>, Object>() {
            
            public Object call(ServiceResponse<Object> response) {
                return response.body();
            }
        });
    }

    /**
     * Get Json Schema.
     * Get the json schema schematics for the provided schema.
     *
     * @param schemaId Schema Id
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Object object
     */
    public Observable<ServiceResponse<Object>> getWithServiceResponseAsync(String schemaId) {
        if (schemaId == null) {
            throw new IllegalArgumentException("Parameter schemaId is required and cannot be null.");
        }
        return service.get(schemaId)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<Object>>>() {
                
                public Observable<ServiceResponse<Object>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<Object> clientResponse = getDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<Object> getDelegate(Response<ResponseBody> response) throws RestException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<Object, RestException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<Object>() { }.getType())
                .register(401, new TypeToken<Void>() { }.getType())
                .register(429, new TypeToken<Void>() { }.getType())
                .register(500, new TypeToken<PictureparkException>() { }.getType())
                .build(response);
    }

}
