/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The AudioStream model.
 */
public class AudioStream {
    /**
     * The bitRate property.
     */
    @JsonProperty(value = "bitRate")
    private String bitRate;

    /**
     * The bitRateMode property.
     */
    @JsonProperty(value = "bitRateMode")
    private String bitRateMode;

    /**
     * The channels property.
     */
    @JsonProperty(value = "channels")
    private String channels;

    /**
     * The channelPositions property.
     */
    @JsonProperty(value = "channelPositions")
    private String channelPositions;

    /**
     * The codec property.
     */
    @JsonProperty(value = "codec")
    private String codec;

    /**
     * The durationInSeconds property.
     */
    @JsonProperty(value = "durationInSeconds")
    private Double durationInSeconds;

    /**
     * The format property.
     */
    @JsonProperty(value = "format")
    private String format;

    /**
     * The language property.
     */
    @JsonProperty(value = "language")
    private String language;

    /**
     * The resolution property.
     */
    @JsonProperty(value = "resolution")
    private Integer resolution;

    /**
     * The samplingRate property.
     */
    @JsonProperty(value = "samplingRate")
    private Integer samplingRate;

    /**
     * The streamSize property.
     */
    @JsonProperty(value = "streamSize")
    private Long streamSize;

    /**
     * Get the bitRate value.
     *
     * @return the bitRate value
     */
    public String bitRate() {
        return this.bitRate;
    }

    /**
     * Set the bitRate value.
     *
     * @param bitRate the bitRate value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withBitRate(String bitRate) {
        this.bitRate = bitRate;
        return this;
    }

    /**
     * Get the bitRateMode value.
     *
     * @return the bitRateMode value
     */
    public String bitRateMode() {
        return this.bitRateMode;
    }

    /**
     * Set the bitRateMode value.
     *
     * @param bitRateMode the bitRateMode value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withBitRateMode(String bitRateMode) {
        this.bitRateMode = bitRateMode;
        return this;
    }

    /**
     * Get the channels value.
     *
     * @return the channels value
     */
    public String channels() {
        return this.channels;
    }

    /**
     * Set the channels value.
     *
     * @param channels the channels value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withChannels(String channels) {
        this.channels = channels;
        return this;
    }

    /**
     * Get the channelPositions value.
     *
     * @return the channelPositions value
     */
    public String channelPositions() {
        return this.channelPositions;
    }

    /**
     * Set the channelPositions value.
     *
     * @param channelPositions the channelPositions value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withChannelPositions(String channelPositions) {
        this.channelPositions = channelPositions;
        return this;
    }

    /**
     * Get the codec value.
     *
     * @return the codec value
     */
    public String codec() {
        return this.codec;
    }

    /**
     * Set the codec value.
     *
     * @param codec the codec value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withCodec(String codec) {
        this.codec = codec;
        return this;
    }

    /**
     * Get the durationInSeconds value.
     *
     * @return the durationInSeconds value
     */
    public Double durationInSeconds() {
        return this.durationInSeconds;
    }

    /**
     * Set the durationInSeconds value.
     *
     * @param durationInSeconds the durationInSeconds value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withDurationInSeconds(Double durationInSeconds) {
        this.durationInSeconds = durationInSeconds;
        return this;
    }

    /**
     * Get the format value.
     *
     * @return the format value
     */
    public String format() {
        return this.format;
    }

    /**
     * Set the format value.
     *
     * @param format the format value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withFormat(String format) {
        this.format = format;
        return this;
    }

    /**
     * Get the language value.
     *
     * @return the language value
     */
    public String language() {
        return this.language;
    }

    /**
     * Set the language value.
     *
     * @param language the language value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withLanguage(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get the resolution value.
     *
     * @return the resolution value
     */
    public Integer resolution() {
        return this.resolution;
    }

    /**
     * Set the resolution value.
     *
     * @param resolution the resolution value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withResolution(Integer resolution) {
        this.resolution = resolution;
        return this;
    }

    /**
     * Get the samplingRate value.
     *
     * @return the samplingRate value
     */
    public Integer samplingRate() {
        return this.samplingRate;
    }

    /**
     * Set the samplingRate value.
     *
     * @param samplingRate the samplingRate value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withSamplingRate(Integer samplingRate) {
        this.samplingRate = samplingRate;
        return this;
    }

    /**
     * Get the streamSize value.
     *
     * @return the streamSize value
     */
    public Long streamSize() {
        return this.streamSize;
    }

    /**
     * Set the streamSize value.
     *
     * @param streamSize the streamSize value to set
     * @return the AudioStream object itself.
     */
    public AudioStream withStreamSize(Long streamSize) {
        this.streamSize = streamSize;
        return this;
    }

}
