/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ContentOwnershipTransferRequest model.
 */
public class ContentOwnershipTransferRequest {
    /**
     * The content id.
     */
    @JsonProperty(value = "contentId")
    private String contentId;

    /**
     * The id of the user to whom the content document has to be transfered to.
     */
    @JsonProperty(value = "transferUserId")
    private String transferUserId;

    /**
     * Get the contentId value.
     *
     * @return the contentId value
     */
    public String contentId() {
        return this.contentId;
    }

    /**
     * Set the contentId value.
     *
     * @param contentId the contentId value to set
     * @return the ContentOwnershipTransferRequest object itself.
     */
    public ContentOwnershipTransferRequest withContentId(String contentId) {
        this.contentId = contentId;
        return this;
    }

    /**
     * Get the transferUserId value.
     *
     * @return the transferUserId value
     */
    public String transferUserId() {
        return this.transferUserId;
    }

    /**
     * Set the transferUserId value.
     *
     * @param transferUserId the transferUserId value to set
     * @return the ContentOwnershipTransferRequest object itself.
     */
    public ContentOwnershipTransferRequest withTransferUserId(String transferUserId) {
        this.transferUserId = transferUserId;
        return this;
    }

}
