/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A request structure for creating a content document.
 */
public class CreateContentRequest {
    /**
     * The id of a schema with schema type content.
     */
    @JsonProperty(value = "contentSchemaId")
    private String contentSchemaId;

    /**
     * An optional id list of schemas with schema type layer.
     */
    @JsonProperty(value = "layerSchemaIds")
    private List<String> layerSchemaIds;

    /**
     * The content data of the content document.
     */
    @JsonProperty(value = "content")
    private Object content;

    /**
     * The metadata property.
     */
    @JsonProperty(value = "metadata")
    private Map<String, Object> metadata;

    /**
     * An optional id list of content permission sets.
     */
    @JsonProperty(value = "contentPermissionSetIds")
    private List<String> contentPermissionSetIds;

    /**
     * Get the contentSchemaId value.
     *
     * @return the contentSchemaId value
     */
    public String contentSchemaId() {
        return this.contentSchemaId;
    }

    /**
     * Set the contentSchemaId value.
     *
     * @param contentSchemaId the contentSchemaId value to set
     * @return the CreateContentRequest object itself.
     */
    public CreateContentRequest withContentSchemaId(String contentSchemaId) {
        this.contentSchemaId = contentSchemaId;
        return this;
    }

    /**
     * Get the layerSchemaIds value.
     *
     * @return the layerSchemaIds value
     */
    public List<String> layerSchemaIds() {
        return this.layerSchemaIds;
    }

    /**
     * Set the layerSchemaIds value.
     *
     * @param layerSchemaIds the layerSchemaIds value to set
     * @return the CreateContentRequest object itself.
     */
    public CreateContentRequest withLayerSchemaIds(List<String> layerSchemaIds) {
        this.layerSchemaIds = layerSchemaIds;
        return this;
    }

    /**
     * Get the content value.
     *
     * @return the content value
     */
    public Object content() {
        return this.content;
    }

    /**
     * Set the content value.
     *
     * @param content the content value to set
     * @return the CreateContentRequest object itself.
     */
    public CreateContentRequest withContent(Object content) {
        this.content = content;
        return this;
    }

    /**
     * Get the metadata value.
     *
     * @return the metadata value
     */
    public Map<String, Object> metadata() {
        return this.metadata;
    }

    /**
     * Set the metadata value.
     *
     * @param metadata the metadata value to set
     * @return the CreateContentRequest object itself.
     */
    public CreateContentRequest withMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get the contentPermissionSetIds value.
     *
     * @return the contentPermissionSetIds value
     */
    public List<String> contentPermissionSetIds() {
        return this.contentPermissionSetIds;
    }

    /**
     * Set the contentPermissionSetIds value.
     *
     * @param contentPermissionSetIds the contentPermissionSetIds value to set
     * @return the CreateContentRequest object itself.
     */
    public CreateContentRequest withContentPermissionSetIds(List<String> contentPermissionSetIds) {
        this.contentPermissionSetIds = contentPermissionSetIds;
        return this;
    }

}
