/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ExifAux model.
 */
public class ExifAux {
    /**
     * The lens property.
     */
    @JsonProperty(value = "lens")
    private String lens;

    /**
     * The serialNumber property.
     */
    @JsonProperty(value = "serialNumber")
    private String serialNumber;

    /**
     * Get the lens value.
     *
     * @return the lens value
     */
    public String lens() {
        return this.lens;
    }

    /**
     * Set the lens value.
     *
     * @param lens the lens value to set
     * @return the ExifAux object itself.
     */
    public ExifAux withLens(String lens) {
        this.lens = lens;
        return this;
    }

    /**
     * Get the serialNumber value.
     *
     * @return the serialNumber value
     */
    public String serialNumber() {
        return this.serialNumber;
    }

    /**
     * Set the serialNumber value.
     *
     * @param serialNumber the serialNumber value to set
     * @return the ExifAux object itself.
     */
    public ExifAux withSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
        return this;
    }

}
