/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response that tells if exists.
 */
public class ExistsResponse {
    /**
     * Gets or sets a value indicating whether it exists.
     */
    @JsonProperty(value = "exists", required = true)
    private boolean exists;

    /**
     * Get the exists value.
     *
     * @return the exists value
     */
    public boolean exists() {
        return this.exists;
    }

    /**
     * Set the exists value.
     *
     * @param exists the exists value to set
     * @return the ExistsResponse object itself.
     */
    public ExistsResponse withExists(boolean exists) {
        this.exists = exists;
        return this;
    }

}
