/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The InvalidUserOrPasswordException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("InvalidUserOrPasswordException")
public class InvalidUserOrPasswordException extends PictureparkException {
    /**
     * The customerId property.
     */
    @JsonProperty(value = "customerId")
    private String customerId;

    /**
     * Get the customerId value.
     *
     * @return the customerId value
     */
    public String customerId() {
        return this.customerId;
    }

    /**
     * Set the customerId value.
     *
     * @param customerId the customerId value to set
     * @return the InvalidUserOrPasswordException object itself.
     */
    public InvalidUserOrPasswordException withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }

}
