/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListItemFieldsFilterUpdateRequest class.
 */
public class ListItemFieldsFilterUpdateRequest {
    /**
     * The searchRequest property.
     */
    @JsonProperty(value = "searchRequest")
    private ListItemSearchRequest searchRequest;

    /**
     * The change commads to be applied to the list items.
     */
    @JsonProperty(value = "changeCommands")
    private List<MetadataValuesSchemaUpdateCommand> changeCommands;

    /**
     * Get the searchRequest value.
     *
     * @return the searchRequest value
     */
    public ListItemSearchRequest searchRequest() {
        return this.searchRequest;
    }

    /**
     * Set the searchRequest value.
     *
     * @param searchRequest the searchRequest value to set
     * @return the ListItemFieldsFilterUpdateRequest object itself.
     */
    public ListItemFieldsFilterUpdateRequest withSearchRequest(ListItemSearchRequest searchRequest) {
        this.searchRequest = searchRequest;
        return this;
    }

    /**
     * Get the changeCommands value.
     *
     * @return the changeCommands value
     */
    public List<MetadataValuesSchemaUpdateCommand> changeCommands() {
        return this.changeCommands;
    }

    /**
     * Set the changeCommands value.
     *
     * @param changeCommands the changeCommands value to set
     * @return the ListItemFieldsFilterUpdateRequest object itself.
     */
    public ListItemFieldsFilterUpdateRequest withChangeCommands(List<MetadataValuesSchemaUpdateCommand> changeCommands) {
        this.changeCommands = changeCommands;
        return this;
    }

}
