/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The LocationInfo model.
 */
public class LocationInfo {
    /**
     * The city property.
     */
    @JsonProperty(value = "city")
    private String city;

    /**
     * The countryCode property.
     */
    @JsonProperty(value = "countryCode")
    private String countryCode;

    /**
     * The countryName property.
     */
    @JsonProperty(value = "countryName")
    private String countryName;

    /**
     * The provinceState property.
     */
    @JsonProperty(value = "provinceState")
    private String provinceState;

    /**
     * The sublocation property.
     */
    @JsonProperty(value = "sublocation")
    private String sublocation;

    /**
     * The worldRegion property.
     */
    @JsonProperty(value = "worldRegion")
    private String worldRegion;

    /**
     * Get the city value.
     *
     * @return the city value
     */
    public String city() {
        return this.city;
    }

    /**
     * Set the city value.
     *
     * @param city the city value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withCity(String city) {
        this.city = city;
        return this;
    }

    /**
     * Get the countryCode value.
     *
     * @return the countryCode value
     */
    public String countryCode() {
        return this.countryCode;
    }

    /**
     * Set the countryCode value.
     *
     * @param countryCode the countryCode value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withCountryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }

    /**
     * Get the countryName value.
     *
     * @return the countryName value
     */
    public String countryName() {
        return this.countryName;
    }

    /**
     * Set the countryName value.
     *
     * @param countryName the countryName value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withCountryName(String countryName) {
        this.countryName = countryName;
        return this;
    }

    /**
     * Get the provinceState value.
     *
     * @return the provinceState value
     */
    public String provinceState() {
        return this.provinceState;
    }

    /**
     * Set the provinceState value.
     *
     * @param provinceState the provinceState value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withProvinceState(String provinceState) {
        this.provinceState = provinceState;
        return this;
    }

    /**
     * Get the sublocation value.
     *
     * @return the sublocation value
     */
    public String sublocation() {
        return this.sublocation;
    }

    /**
     * Set the sublocation value.
     *
     * @param sublocation the sublocation value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withSublocation(String sublocation) {
        this.sublocation = sublocation;
        return this;
    }

    /**
     * Get the worldRegion value.
     *
     * @return the worldRegion value
     */
    public String worldRegion() {
        return this.worldRegion;
    }

    /**
     * Set the worldRegion value.
     *
     * @param worldRegion the worldRegion value to set
     * @return the LocationInfo object itself.
     */
    public LocationInfo withWorldRegion(String worldRegion) {
        this.worldRegion = worldRegion;
        return this;
    }

}
