/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ServiceProviderNotFoundException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ServiceProviderNotFoundException")
public class ServiceProviderNotFoundException extends PictureparkException {
    /**
     * The missingServiceProviderId property.
     */
    @JsonProperty(value = "missingServiceProviderId")
    private String missingServiceProviderId;

    /**
     * Get the missingServiceProviderId value.
     *
     * @return the missingServiceProviderId value
     */
    public String missingServiceProviderId() {
        return this.missingServiceProviderId;
    }

    /**
     * Set the missingServiceProviderId value.
     *
     * @param missingServiceProviderId the missingServiceProviderId value to set
     * @return the ServiceProviderNotFoundException object itself.
     */
    public ServiceProviderNotFoundException withMissingServiceProviderId(String missingServiceProviderId) {
        this.missingServiceProviderId = missingServiceProviderId;
        return this;
    }

}
