/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SortInfo model.
 */
public class SortInfo {
    /**
     * The field property.
     */
    @JsonProperty(value = "field")
    private String field;

    /**
     * Possible values include: 'Asc', 'Desc'.
     */
    @JsonProperty(value = "direction", required = true)
    private String direction;

    /**
     * Get the field value.
     *
     * @return the field value
     */
    public String field() {
        return this.field;
    }

    /**
     * Set the field value.
     *
     * @param field the field value to set
     * @return the SortInfo object itself.
     */
    public SortInfo withField(String field) {
        this.field = field;
        return this;
    }

    /**
     * Get the direction value.
     *
     * @return the direction value
     */
    public String direction() {
        return this.direction;
    }

    /**
     * Set the direction value.
     *
     * @param direction the direction value to set
     * @return the SortInfo object itself.
     */
    public SortInfo withDirection(String direction) {
        this.direction = direction;
        return this;
    }

}
