/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The StorageServerError model.
 */
public class StorageServerError {
    /**
     * The error property.
     */
    @JsonProperty(value = "error")
    private StorageError error;

    /**
     * The status property.
     */
    @JsonProperty(value = "status", required = true)
    private int status;

    /**
     * Get the error value.
     *
     * @return the error value
     */
    public StorageError error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set
     * @return the StorageServerError object itself.
     */
    public StorageServerError withError(StorageError error) {
        this.error = error;
        return this;
    }

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public int status() {
        return this.status;
    }

    /**
     * Set the status value.
     *
     * @param status the status value to set
     * @return the StorageServerError object itself.
     */
    public StorageServerError withStatus(int status) {
        this.status = status;
        return this;
    }

}
