/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The XmpGImg model.
 */
public class XmpGImg {
    /**
     * Possible values include: 'JPEG'.
     */
    @JsonProperty(value = "format")
    private String format;

    /**
     * The width property.
     */
    @JsonProperty(value = "width")
    private Integer width;

    /**
     * The height property.
     */
    @JsonProperty(value = "height")
    private Integer height;

    /**
     * The image property.
     */
    @JsonProperty(value = "image")
    private String image;

    /**
     * Get the format value.
     *
     * @return the format value
     */
    public String format() {
        return this.format;
    }

    /**
     * Set the format value.
     *
     * @param format the format value to set
     * @return the XmpGImg object itself.
     */
    public XmpGImg withFormat(String format) {
        this.format = format;
        return this;
    }

    /**
     * Get the width value.
     *
     * @return the width value
     */
    public Integer width() {
        return this.width;
    }

    /**
     * Set the width value.
     *
     * @param width the width value to set
     * @return the XmpGImg object itself.
     */
    public XmpGImg withWidth(Integer width) {
        this.width = width;
        return this;
    }

    /**
     * Get the height value.
     *
     * @return the height value
     */
    public Integer height() {
        return this.height;
    }

    /**
     * Set the height value.
     *
     * @param height the height value to set
     * @return the XmpGImg object itself.
     */
    public XmpGImg withHeight(Integer height) {
        this.height = height;
        return this;
    }

    /**
     * Get the image value.
     *
     * @return the image value
     */
    public String image() {
        return this.image;
    }

    /**
     * Set the image value.
     *
     * @param image the image value to set
     * @return the XmpGImg object itself.
     */
    public XmpGImg withImage(String image) {
        this.image = image;
        return this;
    }

}
