/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ChildFilter model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ChildFilter")
public class ChildFilter extends FilterBase {
    /**
     * The elastic search index type to filter as a child.
     */
    @JsonProperty(value = "childType")
    private String childType;

    /**
     * The filter property.
     */
    @JsonProperty(value = "filter")
    private FilterBase filter;

    /**
     * Get the childType value.
     *
     * @return the childType value
     */
    public String childType() {
        return this.childType;
    }

    /**
     * Set the childType value.
     *
     * @param childType the childType value to set
     * @return the ChildFilter object itself.
     */
    public ChildFilter withChildType(String childType) {
        this.childType = childType;
        return this;
    }

    /**
     * Get the filter value.
     *
     * @return the filter value
     */
    public FilterBase filter() {
        return this.filter;
    }

    /**
     * Set the filter value.
     *
     * @param filter the filter value to set
     * @return the ChildFilter object itself.
     */
    public ChildFilter withFilter(FilterBase filter) {
        this.filter = filter;
        return this;
    }

}
