/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ContentsOwnershipTransferRequest model.
 */
public class ContentsOwnershipTransferRequest {
    /**
     * The content ids.
     */
    @JsonProperty(value = "contentIds")
    private List<String> contentIds;

    /**
     * The id of user to whom the content documents have to be transfered to.
     */
    @JsonProperty(value = "transferUserId")
    private String transferUserId;

    /**
     * Get the contentIds value.
     *
     * @return the contentIds value
     */
    public List<String> contentIds() {
        return this.contentIds;
    }

    /**
     * Set the contentIds value.
     *
     * @param contentIds the contentIds value to set
     * @return the ContentsOwnershipTransferRequest object itself.
     */
    public ContentsOwnershipTransferRequest withContentIds(List<String> contentIds) {
        this.contentIds = contentIds;
        return this;
    }

    /**
     * Get the transferUserId value.
     *
     * @return the transferUserId value
     */
    public String transferUserId() {
        return this.transferUserId;
    }

    /**
     * Set the transferUserId value.
     *
     * @param transferUserId the transferUserId value to set
     * @return the ContentsOwnershipTransferRequest object itself.
     */
    public ContentsOwnershipTransferRequest withTransferUserId(String transferUserId) {
        this.transferUserId = transferUserId;
        return this;
    }

}
