/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The NotFoundException model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("NotFoundException")
public class NotFoundException extends PictureparkBusinessException {
    /**
     * The reference property.
     */
    @JsonProperty(value = "reference")
    private String reference;

    /**
     * Get the reference value.
     *
     * @return the reference value
     */
    public String reference() {
        return this.reference;
    }

    /**
     * Set the reference value.
     *
     * @param reference the reference value to set
     * @return the NotFoundException object itself.
     */
    public NotFoundException withReference(String reference) {
        this.reference = reference;
        return this;
    }

}
