/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package foobar.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * An analyzer using the path hierarchy tokenizer.
 * https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("PathHierarchyAnalyzer")
public class PathHierarchyAnalyzer extends AnalyzerBase {
    /**
     * The fieldSuffix property.
     */
    @JsonProperty(value = "fieldSuffix")
    private String fieldSuffix;

    /**
     * Get the fieldSuffix value.
     *
     * @return the fieldSuffix value
     */
    public String fieldSuffix() {
        return this.fieldSuffix;
    }

    /**
     * Set the fieldSuffix value.
     *
     * @param fieldSuffix the fieldSuffix value to set
     * @return the PathHierarchyAnalyzer object itself.
     */
    public PathHierarchyAnalyzer withFieldSuffix(String fieldSuffix) {
        this.fieldSuffix = fieldSuffix;
        return this;
    }

}
