/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.PictureparkException;
import io.swagger.client.model.UserProfile;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileApi
 */
@Ignore
public class ProfileApiTest {

    private final ProfileApi api = new ProfileApi();

    
    /**
     * Get
     *
     * Get profile of currently logged in user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void profileGetTest() throws ApiException {
        UserProfile response = api.profileGet();

        // TODO: test validations
    }
    
    /**
     * Update
     *
     * Updates profile of currently logged in user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void profileUpdateTest() throws ApiException {
        UserProfile profile = null;
        UserProfile response = api.profileUpdate(profile);

        // TODO: test validations
    }
    
}
